package dev.jux.intellij.resolve

import com.intellij.navigation.ItemPresentation
import com.intellij.openapi.project.Project
import com.intellij.openapi.roots.AdditionalLibraryRootsProvider
import com.intellij.openapi.roots.SyntheticLibrary
import com.intellij.openapi.vfs.VirtualFile
import dev.jux.intellij.JuxIcons
import javax.swing.Icon

/**
 * Puts the toolchain's generated `.jux.d` stubs — the standard library and
 * every bound Rust crate — into the IDE's index as an external library.
 *
 * This is what makes the plugin know the standard library instead of
 * describing it. The stubs are Jux source generated from the installed
 * toolchain's own view of each API ([JuxStubRoots] finds them), so once they
 * are indexed the machinery that already exists does the rest: `Vec` resolves
 * to a declaration, `v.` completes the methods `Vec` really has on THIS
 * install, go-to-definition opens the signature, and the unresolved-reference
 * inspection stops guessing. A crate the user adds tomorrow is picked up when
 * its stub is generated, with no plugin release.
 *
 * The library is read-only and shows under **External Libraries** so the user
 * can see exactly which surface the editor is resolving against.
 */
class JuxLibraryRootsProvider : AdditionalLibraryRootsProvider() {

    override fun getAdditionalProjectLibraries(project: Project): Collection<SyntheticLibrary> {
        if (isUnitTestMode()) return emptyList()
        val roots = JuxStubRoots.externalRootFiles()
        if (roots.isEmpty()) return emptyList()
        return listOf(JuxStubLibrary(roots))
    }

    /**
     * Watching the roots means a stub regenerated by a build (a new crate
     * bound, the std cache refreshed after a toolchain upgrade) re-indexes on
     * its own, rather than after a restart.
     */
    override fun getRootsToWatch(project: Project): Collection<VirtualFile> =
        if (isUnitTestMode()) emptyList() else JuxStubRoots.externalRootFiles()

    /**
     * Tests get no external roots.
     *
     * Discovery reads whatever toolchain the machine has installed, which is
     * exactly right in an IDE and exactly wrong in a test: a fixture would
     * silently index the developer's own standard library, so the same test
     * would pass here, fail on a machine with a different toolchain, and behave
     * differently again on CI where none is installed. Discovery itself is
     * covered directly ([dev.jux.intellij.resolve.JuxStubIndexTest]), and the
     * downstream behaviour is covered with stubs the fixture puts in the
     * project, where their content is known.
     */
    private fun isUnitTestMode(): Boolean =
        com.intellij.openapi.application.ApplicationManager.getApplication()?.isUnitTestMode == true

    private class JuxStubLibrary(private val roots: List<VirtualFile>) :
        SyntheticLibrary(), ItemPresentation {

        override fun getSourceRoots(): Collection<VirtualFile> = roots

        override fun getPresentableText(): String = "Jux standard library and crate stubs"

        override fun getIcon(unused: Boolean): Icon = JuxIcons.FILE

        // Two providers for the same roots must compare equal, or the platform
        // re-indexes them on every project open.
        override fun equals(other: Any?): Boolean =
            other is JuxStubLibrary && other.roots == roots

        override fun hashCode(): Int = roots.hashCode()
    }
}
