package dev.jux.intellij.resolve

import com.intellij.navigation.ItemPresentation
import com.intellij.openapi.project.Project
import com.intellij.openapi.roots.AdditionalLibraryRootsProvider
import com.intellij.openapi.roots.SyntheticLibrary
import com.intellij.openapi.vfs.VirtualFile
import dev.jux.intellij.JuxIcons
import javax.swing.Icon

/**
 * Puts the toolchain's generated `.jux.d` stubs — the standard library and
 * every bound Rust crate — into the IDE's index as an external library.
 *
 * This is what makes the plugin know the standard library instead of
 * describing it. The stubs are Jux source generated from the installed
 * toolchain's own view of each API ([JuxStubRoots] finds them), so once they
 * are indexed the machinery that already exists does the rest: `Vec` resolves
 * to a declaration, `v.` completes the methods `Vec` really has on THIS
 * install, go-to-definition opens the signature, and the unresolved-reference
 * inspection stops guessing. A crate the user adds tomorrow is picked up when
 * its stub is generated, with no plugin release.
 *
 * The library is read-only and shows under **External Libraries** so the user
 * can see exactly which surface the editor is resolving against.
 */
class JuxLibraryRootsProvider : AdditionalLibraryRootsProvider() {

    override fun getAdditionalProjectLibraries(project: Project): Collection<SyntheticLibrary> {
        val out = ArrayList<SyntheticLibrary>()
        // Every Jux package the project depends on from outside its content:
        // path dependencies and git checkouts, transitively, each its own
        // entry under External Libraries (as Java shows one per jar). Read
        // from the manifests, so it is right in tests as well.
        for ((pkg, roots) in dev.jux.intellij.project.JuxDependencies.snapshot(project).libraryRoots()) {
            if (roots.isNotEmpty()) out.add(JuxPackageLibrary(pkg.name ?: pkg.root.name, pkg.origin.name.lowercase(), roots))
        }
        if (!isUnitTestMode()) {
            val roots = JuxStubRoots.externalRootFiles()
            if (roots.isNotEmpty()) out.add(JuxStubLibrary(roots))
        }
        // The compiler's own `jux.std` sources, bundled with the plugin. Fixed
        // by the build rather than read from the machine, so tests get them too.
        JuxBundledStd.root()?.let { out.add(JuxStdLibrary(it)) }
        return out
    }

    /**
     * Watching the roots means a stub regenerated by a build (a new crate
     * bound, the std cache refreshed after a toolchain upgrade) or an edit in a
     * path dependency re-indexes on its own, rather than after a restart.
     */
    override fun getRootsToWatch(project: Project): Collection<VirtualFile> {
        val snapshot = dev.jux.intellij.project.JuxDependencies.snapshot(project)
        // Path-sourced Rust crates are watched too (not indexed): an edit to
        // their `.rs` sources is what tells JuxDependencySync to regenerate
        // the crate's stub.
        val deps = snapshot.libraryRoots().values.flatten() + snapshot.foreignDeps.mapNotNull { it.crateDir() }
        return if (isUnitTestMode()) deps else deps + JuxStubRoots.externalRootFiles()
    }

    /**
     * Tests get no external roots.
     *
     * Discovery reads whatever toolchain the machine has installed, which is
     * exactly right in an IDE and exactly wrong in a test: a fixture would
     * silently index the developer's own standard library, so the same test
     * would pass here, fail on a machine with a different toolchain, and behave
     * differently again on CI where none is installed. Discovery itself is
     * covered directly ([dev.jux.intellij.resolve.JuxStubIndexTest]), and the
     * downstream behaviour is covered with stubs the fixture puts in the
     * project, where their content is known.
     */
    private fun isUnitTestMode(): Boolean =
        com.intellij.openapi.application.ApplicationManager.getApplication()?.isUnitTestMode == true

    /**
     * One Jux package the project depends on: a path dependency or a git
     * checkout, its sources plus its own generated crate stubs, read-only.
     */
    private class JuxPackageLibrary(
        private val name: String,
        private val origin: String,
        private val roots: List<VirtualFile>,
    ) : SyntheticLibrary(), ItemPresentation {

        override fun getSourceRoots(): Collection<VirtualFile> = roots

        override fun getPresentableText(): String = "Jux: $name ($origin)"

        override fun getIcon(unused: Boolean): Icon = JuxIcons.FILE

        override fun equals(other: Any?): Boolean =
            other is JuxPackageLibrary && other.name == name && other.roots == roots

        override fun hashCode(): Int = 31 * name.hashCode() + roots.hashCode()
    }

    /** The bundled `jux.std` sources ([JuxBundledStd]), read-only. */
    private class JuxStdLibrary(private val root: VirtualFile) : SyntheticLibrary(), ItemPresentation {

        override fun getSourceRoots(): Collection<VirtualFile> = listOf(root)

        override fun getPresentableText(): String = "Jux: jux.std"

        override fun getIcon(unused: Boolean): Icon = JuxIcons.FILE

        override fun equals(other: Any?): Boolean = other is JuxStdLibrary && other.root == root

        override fun hashCode(): Int = root.hashCode()
    }

    private class JuxStubLibrary(private val roots: List<VirtualFile>) :
        SyntheticLibrary(), ItemPresentation {

        override fun getSourceRoots(): Collection<VirtualFile> = roots

        override fun getPresentableText(): String = "Jux standard library and crate stubs"

        override fun getIcon(unused: Boolean): Icon = JuxIcons.FILE

        // Two providers for the same roots must compare equal, or the platform
        // re-indexes them on every project open.
        override fun equals(other: Any?): Boolean =
            other is JuxStubLibrary && other.roots == roots

        override fun hashCode(): Int = roots.hashCode()
    }
}
