//! Embedded `jux.std` sources — generated by inlining the former on-disk
//! `jux.std/` tree so the compiler is **self-contained** (no loose stdlib
//! folder must ship next to the binary). Each entry is
//! `(relative-path, source)`; [`crate::stdlib::load_std_sources`] turns them
//! into `SourceFile`s under a synthetic `jux.std/<path>` path so source-map
//! markers and diagnostics read the same as before. Regenerate by re-running
//! the inliner if the stdlib declarations change.

/// `(relative-path, source-text)` for every former `jux.std/*.jux` file.
pub const STDLIB_SOURCES: &[(&str, &str)] = &[
    ("collections/ArrayList.jux", r###"/**
 * jux.std.collections.ArrayList<T>
 *
 * Vec-backed concrete `List<T>` — the default growable list.
 * Mirrors `java.util.ArrayList<T>`.
 *
 * **Implementation status.** ArrayList is one of the small set
 * of "compiler primitives" the Jux backend knows natively — it
 * lowers to Rust's `Vec<T>` at every use site (struct shape,
 * `new` expression, and every method below). The Jux source
 * here documents the API contract and gives tycheck concrete
 * method signatures to verify against; method bodies are
 * unreachable in any real run.
 *
 * Higher-level collection types (Stack, Queue, LinkedList, …)
 * land as pure-Jux source on top of ArrayList in follow-up
 * work — no compiler changes needed for those.
 */
package jux.std.collections;

import jux.std.exceptions.UnsupportedOperationException;

public class ArrayList<T> implements List<T> {
    /**
     * Construct an empty list. Capacity grows on demand.
     */
    public ArrayList() {}

    /**
     * Number of elements currently stored.
     */
    public int size() { throw new UnsupportedOperationException("intrinsic"); }

    /**
     * Convenience test against `size()`.
     *
     * @return true iff `size() == 0`.
     */
    public bool isEmpty() { throw new UnsupportedOperationException("intrinsic"); }

    /**
     * Linear scan for `value` using element equality.
     */
    public bool contains(T value) { throw new UnsupportedOperationException("intrinsic"); }

    /**
     * Append `value` to the end. Always grows.
     */
    public bool add(T value) { throw new UnsupportedOperationException("intrinsic"); }

    /**
     * Remove the first occurrence of `value`. Returns true on
     * a successful removal.
     */
    public bool remove(T value) { throw new UnsupportedOperationException("intrinsic"); }

    /**
     * Drop every element.
     */
    public void clear() { throw new UnsupportedOperationException("intrinsic"); }

    /**
     * Element at position `index`. Throws on out-of-bounds.
     */
    public T get(int index) { throw new UnsupportedOperationException("intrinsic"); }

    /**
     * Overwrite at `index`, returning the previous value.
     */
    public T set(int index, T value) { throw new UnsupportedOperationException("intrinsic"); }

    /**
     * Insert `value` at `index`, shifting later elements right.
     */
    public void insert(int index, T value) { throw new UnsupportedOperationException("intrinsic"); }

    /**
     * Find the first index of `value`, or -1 when not present.
     */
    public int indexOf(T value) { throw new UnsupportedOperationException("intrinsic"); }

    /**
     * First element. Throws on empty.
     */
    public T first() { throw new UnsupportedOperationException("intrinsic"); }

    /**
     * Last element. Throws on empty.
     */
    public T last() { throw new UnsupportedOperationException("intrinsic"); }

    /**
     * Reverse the list in place.
     */
    public void reverse() { throw new UnsupportedOperationException("intrinsic"); }

    /**
     * Sort in place using natural ordering.
     */
    public void sort() { throw new UnsupportedOperationException("intrinsic"); }

    /**
     * Join elements with `sep` (only typed for `List<String>`).
     */
    public String join(String sep) { throw new UnsupportedOperationException("intrinsic"); }

    /**
     * Fresh cursor (not yet wired in Phase-1).
     */
    public Iterator<T> iterator() { throw new UnsupportedOperationException("intrinsic"); }
}
"###),
    ("collections/Collection.jux", r###"/**
 * jux.std.collections.Collection<T>
 *
 * Common operations on any group of `T`-valued items. Sits
 * between `Iterable<T>` and the concrete collection types
 * (`List<T>`, `Set<T>`, `Queue<T>`, …).
 *
 * Mirrors `java.util.Collection<T>` minus the bulk-operation
 * variants (`addAll`, `removeAll`, `retainAll`) — those land
 * when the stream / functional pipeline lands.
 */
package jux.std.collections;

public interface Collection<T> extends Iterable<T> {
    /**
     * Number of elements currently in the collection.
     *
     * @return non-negative count.
     */
    int size();

    /**
     * Convenience test against `size()`.
     *
     * @return true iff `size() == 0`.
     */
    bool isEmpty();

    /**
     * Membership test using element equality.
     *
     * @return true iff at least one element equals `value`.
     */
    bool contains(T value);

    /**
     * Add `value` to the collection.
     *
     * @return true when the collection changed (lists always do;
     *         sets may return false when value was already
     *         present).
     */
    bool add(T value);

    /**
     * Remove the first occurrence of `value`.
     *
     * @return true when a removal happened, false otherwise.
     */
    bool remove(T value);

    /**
     * Drop every element. After this returns, `isEmpty()` is
     * true.
     */
    void clear();
}
"###),
    ("collections/HashMap.jux", r###"/**
 * jux.std.collections.HashMap<K, V>
 *
 * Hash-backed concrete `Map<K, V>` — the default associative
 * container. Mirrors `java.util.HashMap<K, V>`.
 *
 * **Implementation status.** HashMap is a "compiler primitive"
 * — the backend knows the FQN `jux.std.collections.HashMap`
 * and routes every type position, `new` expression, and method
 * call to Rust's `std::collections::HashMap<K, V>`. Method
 * bodies below are unreachable; they exist so tycheck has a
 * concrete contract that matches the `Map<K, V>` interface.
 */
package jux.std.collections;

import jux.std.exceptions.UnsupportedOperationException;

public class HashMap<K, V> implements Map<K, V> {
    /**
     * Construct an empty map.
     */
    public HashMap() {}

    /** Number of (key, value) entries. */
    public int size() { throw new UnsupportedOperationException("intrinsic"); }

    /** True iff `size() == 0`. */
    public bool isEmpty() { throw new UnsupportedOperationException("intrinsic"); }

    /** True iff `key` is bound in this map. */
    public bool contains(K key) { throw new UnsupportedOperationException("intrinsic"); }

    /** Read the value bound to `key`. Panics on missing key. */
    public V get(K key) { throw new UnsupportedOperationException("intrinsic"); }

    /** Insert or overwrite the binding for `key`. */
    public V put(K key, V value) { throw new UnsupportedOperationException("intrinsic"); }

    /** Drop the binding for `key`. */
    public V remove(K key) { throw new UnsupportedOperationException("intrinsic"); }

    /** Snapshot list of keys. */
    public List<K> keys() { throw new UnsupportedOperationException("intrinsic"); }

    /** Snapshot list of values. */
    public List<V> values() { throw new UnsupportedOperationException("intrinsic"); }

    /** Drop every entry. */
    public void clear() { throw new UnsupportedOperationException("intrinsic"); }
}
"###),
    ("collections/HashSet.jux", r###"/**
 * jux.std.collections.HashSet<T>
 *
 * Hash-backed concrete `Set<T>` — the default no-duplicate
 * collection. Mirrors `java.util.HashSet<T>`.
 *
 * **Implementation status.** HashSet is a "compiler primitive"
 * — the backend lowers it to Rust's
 * `std::collections::HashSet<T>` at every use site.
 */
package jux.std.collections;

import jux.std.exceptions.UnsupportedOperationException;

public class HashSet<T> implements Set<T> {
    /**
     * Construct an empty set.
     */
    public HashSet() {}

    /** Number of distinct elements. */
    public int size() { throw new UnsupportedOperationException("intrinsic"); }

    /** True iff `size() == 0`. */
    public bool isEmpty() { throw new UnsupportedOperationException("intrinsic"); }

    /** Membership test. */
    public bool contains(T value) { throw new UnsupportedOperationException("intrinsic"); }

    /**
     * Add a member; returns true when the set didn't already
     * contain `value`.
     */
    public bool add(T value) { throw new UnsupportedOperationException("intrinsic"); }

    /**
     * Drop a member; returns true when something was actually
     * removed.
     */
    public bool remove(T value) { throw new UnsupportedOperationException("intrinsic"); }

    /** Drop every element. */
    public void clear() { throw new UnsupportedOperationException("intrinsic"); }

    /** Fresh cursor (not yet wired in Phase-1). */
    public Iterator<T> iterator() { throw new UnsupportedOperationException("intrinsic"); }
}
"###),
    ("collections/Iterable.jux", r###"/**
 * jux.std.collections.Iterable<T>
 *
 * Root of every collection in the Jux stdlib. Anything that can
 * be stepped through with `for (T x : it)` implements this
 * interface. Mirrors `java.lang.Iterable<T>`.
 *
 * Phase-1 model: a single `iterator()` method returns an
 * `Iterator<T>` handle. The for-each loop machinery in the
 * backend special-cases known concrete iterables (`ArrayList`,
 * `HashMap`'s `keys()` / `values()`) — implementing this
 * interface from user code is a contract assertion today;
 * runtime dispatch through the trait shape lands when the
 * dyn-dispatch story matures.
 */
package jux.std.collections;

public interface Iterable<T> {
    /**
     * Build a fresh cursor that walks every element of this
     * collection in its natural order.
     *
     * @return a new iterator starting before the first element.
     */
    Iterator<T> iterator();
}
"###),
    ("collections/Iterator.jux", r###"/**
 * jux.std.collections.Iterator<T>
 *
 * Cursor over an `Iterable<T>`. Mirrors `java.util.Iterator<T>`
 * minus `remove()` (a Phase-2 addition).
 *
 * Typical use:
 *
 *     final Iterator<int> it = xs.iterator();
 *     while (it.hasNext()) {
 *         final int n = it.next();
 *         // ...
 *     }
 */
package jux.std.collections;

public interface Iterator<T> {
    /**
     * Cheap "is there more?" probe.
     *
     * @return true iff a subsequent `next()` call would succeed.
     */
    bool hasNext();

    /**
     * Advance the cursor and yield the value at the new
     * position.
     *
     * @return the next element.
     * @throws NoSuchElementException when no more elements
     *         remain.
     */
    T next();
}
"###),
    ("collections/List.jux", r###"/**
 * jux.std.collections.List<T>
 *
 * Ordered, indexed collection. Mirrors `java.util.List<T>`.
 *
 * Java parallel: any `class Foo<T> implements List<T> { … }`
 * works the same way `class MyList implements
 * java.util.List<T>` does in Java. The concrete `ArrayList<T>`
 * is the Vec-backed default; users may swap in their own
 * (linked-list, ring buffer, memory-mapped, etc.).
 */
package jux.std.collections;

public interface List<T> extends Collection<T> {
    /**
     * Element at position `index`.
     *
     * @throws IndexOutOfBoundsException when `index` is outside
     *         `[0, size())`.
     */
    T get(int index);

    /**
     * Replace the element at `index`.
     *
     * @return the old value at that position.
     * @throws IndexOutOfBoundsException on out-of-range index.
     */
    T set(int index, T value);

    /**
     * Insert `value` at `index`, shifting later elements right.
     *
     * @throws IndexOutOfBoundsException when `index < 0` or
     *         `index > size()`.
     */
    void insert(int index, T value);

    /**
     * Locate the first index of `value`.
     *
     * @return matching index, or -1 when not present.
     */
    int indexOf(T value);

    /**
     * First element of the list.
     *
     * @throws NoSuchElementException on an empty list.
     */
    T first();

    /**
     * Last element of the list.
     *
     * @throws NoSuchElementException on an empty list.
     */
    T last();

    /**
     * Reverse the list in place.
     */
    void reverse();

    /**
     * Sort the list in place using the element type's natural
     * ordering. Custom comparators land with `Comparator<T>`
     * in Phase-2.
     */
    void sort();

    /**
     * Concatenate every element with `sep` between adjacent
     * pairs. Defined on the interface so any `List<String>`
     * implementation gets it for free; non-string element types
     * need a Phase-2 `String.format` path.
     */
    String join(String sep);
}
"###),
    ("collections/Map.jux", r###"/**
 * jux.std.collections.Map<K, V>
 *
 * Key/value associative container. Mirrors `java.util.Map<K, V>`.
 *
 * Implementable — `class MyMap<K, V> implements Map<K, V> { … }`
 * is the supported way to write a custom Map. The default
 * implementation is `HashMap<K, V>` (hash-backed; lowers to
 * Rust's `std::collections::HashMap` at the backend).
 */
package jux.std.collections;

public interface Map<K, V> {
    /**
     * Number of (key, value) entries currently in the map.
     *
     * @return non-negative count.
     */
    int size();

    /**
     * Convenience test against `size()`.
     *
     * @return true iff `size() == 0`.
     */
    bool isEmpty();

    /**
     * Check whether `key` is present.
     *
     * @return true iff an entry with key equal to `key` exists.
     */
    bool contains(K key);

    /**
     * Read the value bound to `key`. Pair with `contains` for
     * a guarded read.
     *
     * @return the bound value.
     * @throws NoSuchElementException when `key` is not present.
     */
    V get(K key);

    /**
     * Insert or overwrite the binding for `key`.
     *
     * @return the previous value, or throws when there wasn't
     *         one (Phase-1 limitation — until `V?` is wired,
     *         missing-key returns can't be expressed in the
     *         signature).
     */
    V put(K key, V value);

    /**
     * Drop the binding for `key`.
     *
     * @return the removed value.
     * @throws NoSuchElementException when `key` was not bound.
     */
    V remove(K key);

    /**
     * Snapshot list of every key. Order is unspecified.
     */
    List<K> keys();

    /**
     * Snapshot list of every value. Order is unspecified.
     */
    List<V> values();

    /**
     * Drop every entry. After this returns, `isEmpty()` is true.
     */
    void clear();
}
"###),
    ("collections/Set.jux", r###"/**
 * jux.std.collections.Set<T>
 *
 * Unordered collection with no duplicates. Mirrors
 * `java.util.Set<T>`. The concrete default is `HashSet<T>`
 * (lowered onto Rust's `std::collections::HashSet`); users may
 * implement their own (tree-set, bitset, etc.) by implementing
 * this interface.
 *
 * The base `Collection<T>` already gives us `size`, `isEmpty`,
 * `contains`, `add`, `remove`, and `clear`. Sets add no extra
 * methods at the interface layer — the `add` returns `false`
 * when the value was already a member, which distinguishes
 * set-add from list-add at the call site.
 */
package jux.std.collections;

public interface Set<T> extends Collection<T> {
}
"###),
    ("concurrent/Worker.jux", r###"/**
 * jux.std.concurrent.Worker
 *
 * Entry point for true multi-core parallelism per
 * JUX-ASYNC-ADDENDUM §18.2. `Worker.spawn(closure)` runs the
 * closure on a fresh OS thread from the system pool and
 * returns a `Task<T>` (a Future yielding the closure's return
 * value).
 *
 * **Implementation status.** `Worker.spawn` is a compiler
 * primitive — the backend special-cases the call (closures
 * need a bare `move ||` shape that doesn't fit the generic
 * lambda emit path) and generates the `std::thread::spawn(...)`
 * plus `futures::channel::oneshot` plumbing in the prelude.
 *
 * Package name is `concurrent` (not `async`) because `async`
 * is a reserved keyword in Jux for async-function declarations.
 */
package jux.std.concurrent;

public class Worker {
}
"###),
    ("exceptions/ArithmeticException.jux", r###"/**
 * jux.std.exceptions.ArithmeticException
 *
 * Numeric overflow, divide-by-zero, modulo-by-zero. Mirrors
 * `java.lang.ArithmeticException`.
 */
package jux.std.exceptions;

public class ArithmeticException extends RuntimeException {
    /**
     * Construct an ArithmeticException with a message
     * describing the arithmetic failure.
     */
    public ArithmeticException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/ClassCastException.jux", r###"/**
 * jux.std.exceptions.ClassCastException
 *
 * Runtime cast that the value's actual type doesn't satisfy
 * (e.g. `(Cat) animal` where `animal` is a `Dog`). Mirrors
 * `java.lang.ClassCastException`.
 */
package jux.std.exceptions;

public class ClassCastException extends RuntimeException {
    /**
     * Construct a ClassCastException with a message describing
     * the source and target types.
     */
    public ClassCastException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/Error.jux", r###"/**
 * jux.std.exceptions.Error
 *
 * Unrecoverable failure — out-of-memory, stack overflow,
 * internal invariant violations. Distinct from `Exception` so
 * that `catch (Exception e)` doesn't swallow runtime
 * catastrophes. Mirrors `java.lang.Error`.
 */
package jux.std.exceptions;

public class Error extends Throwable {
    /**
     * Construct an Error with the given diagnostic message.
     */
    public Error(String message) {
        super(message);
    }
}
"###),
    ("exceptions/Exception.jux", r###"/**
 * jux.std.exceptions.Exception
 *
 * Recoverable error condition. The general parent of every
 * exception a Jux program normally catches. Mirrors
 * `java.lang.Exception`.
 *
 * Distinct from `Error` so `catch (Exception e)` doesn't
 * accidentally swallow unrecoverable failures.
 */
package jux.std.exceptions;

public class Exception extends Throwable {
    /**
     * Construct an Exception with the given diagnostic message.
     */
    public Exception(String message) {
        super(message);
    }
}
"###),
    ("exceptions/FileNotFoundException.jux", r###"/**
 * jux.std.exceptions.FileNotFoundException
 *
 * Specialization of `IOException` for the "file doesn't
 * exist" case. Mirrors `java.io.FileNotFoundException`.
 */
package jux.std.exceptions;

public class FileNotFoundException extends IOException {
    /**
     * Construct a FileNotFoundException naming the missing
     * path.
     */
    public FileNotFoundException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/IllegalArgumentException.jux", r###"/**
 * jux.std.exceptions.IllegalArgumentException
 *
 * Argument value violated a method's precondition. Mirrors
 * `java.lang.IllegalArgumentException`.
 */
package jux.std.exceptions;

public class IllegalArgumentException extends RuntimeException {
    /**
     * Construct an IllegalArgumentException with a message
     * describing the precondition that was violated.
     */
    public IllegalArgumentException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/IllegalStateException.jux", r###"/**
 * jux.std.exceptions.IllegalStateException
 *
 * Receiver was in the wrong state for the requested operation
 * (e.g. `iterator.next()` after exhaustion, double-close on a
 * stream). Mirrors `java.lang.IllegalStateException`.
 */
package jux.std.exceptions;

public class IllegalStateException extends RuntimeException {
    /**
     * Construct an IllegalStateException describing the
     * invalid state.
     */
    public IllegalStateException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/IndexOutOfBoundsException.jux", r###"/**
 * jux.std.exceptions.IndexOutOfBoundsException
 *
 * Array / list / string index outside the valid `[0, length)`
 * range. Mirrors `java.lang.IndexOutOfBoundsException`.
 */
package jux.std.exceptions;

public class IndexOutOfBoundsException extends RuntimeException {
    /**
     * Construct an IndexOutOfBoundsException with the given
     * diagnostic message (typically including the offending
     * index and the valid range).
     */
    public IndexOutOfBoundsException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/IOException.jux", r###"/**
 * jux.std.exceptions.IOException
 *
 * I/O failure — file not found, permission denied, broken
 * pipe, socket reset. Mirrors `java.io.IOException` (Java
 * keeps it under `java.io`; we group it under
 * `jux.std.exceptions` so every error type lives in one
 * place).
 */
package jux.std.exceptions;

public class IOException extends Exception {
    /**
     * Construct an IOException describing the I/O failure
     * (path, system error message, etc.).
     */
    public IOException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/NoSuchElementException.jux", r###"/**
 * jux.std.exceptions.NoSuchElementException
 *
 * Iterator exhausted, or `Map.get` / `List.first` / `List.last`
 * called on a collection with no matching element. Mirrors
 * `java.util.NoSuchElementException` (Java puts it in
 * `java.util` because the iterator interface lives there; we
 * collapse the tree under `jux.std.exceptions`).
 */
package jux.std.exceptions;

public class NoSuchElementException extends RuntimeException {
    /**
     * Construct a NoSuchElementException with a message
     * naming the missing element / iteration state.
     */
    public NoSuchElementException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/NullPointerException.jux", r###"/**
 * jux.std.exceptions.NullPointerException
 *
 * Dereference of a `null` value. Mirrors
 * `java.lang.NullPointerException`. The compiler emits this
 * automatically for unchecked nullable unwraps in Phase-2;
 * Phase-1 lets the user throw it manually.
 */
package jux.std.exceptions;

public class NullPointerException extends RuntimeException {
    /**
     * Construct a NullPointerException with the given
     * diagnostic message.
     */
    public NullPointerException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/RuntimeException.jux", r###"/**
 * jux.std.exceptions.RuntimeException
 *
 * Unchecked exceptions — bugs that the program *could* catch
 * but usually shouldn't. Mirrors `java.lang.RuntimeException`.
 * Parent of `NullPointerException`,
 * `IndexOutOfBoundsException`, `IllegalArgumentException`,
 * `ArithmeticException`, etc.
 */
package jux.std.exceptions;

public class RuntimeException extends Exception {
    /**
     * Construct a RuntimeException with the given diagnostic
     * message.
     */
    public RuntimeException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/Throwable.jux", r###"/**
 * jux.std.exceptions.Throwable
 *
 * Root of the exception hierarchy. Every value that can flow
 * through a `throw` statement extends `Throwable`. Mirrors
 * `java.lang.Throwable`.
 *
 * Phase-1 model: carries a message string. Cause chains and
 * stack traces land in a follow-up addendum.
 */
package jux.std.exceptions;

public class Throwable {
    /**
     * Human-readable description of the failure.
     */
    public String message;

    /**
     * Construct a Throwable with the given diagnostic message.
     *
     * @param message text shown in the default panic hook.
     */
    public Throwable(String message) {
        this.message = message;
    }
}
"###),
    ("exceptions/UnsupportedOperationException.jux", r###"/**
 * jux.std.exceptions.UnsupportedOperationException
 *
 * Operation that isn't supported on this receiver — e.g.
 * calling a mutating method on an immutable view. Mirrors
 * `java.lang.UnsupportedOperationException`. Also used by
 * stdlib intrinsic stubs whose bodies the backend replaces.
 */
package jux.std.exceptions;

public class UnsupportedOperationException extends RuntimeException {
    /**
     * Construct an UnsupportedOperationException naming the
     * unsupported operation.
     */
    public UnsupportedOperationException(String message) {
        super(message);
    }
}
"###),
    ("io/File.jux", r###"/**
 * jux.std.io.File
 *
 * Static-method entry point for file I/O. Mirrors a subset of
 * Java's `java.nio.file.Files` (with the cleaner naming of
 * `java.io.File`'s utility methods).
 *
 * **Implementation status.** File's static methods are
 * compiler primitives — the backend recognizes
 * `File.readText`, `File.writeText`, `File.exists` and emits
 * the matching `std::fs::*` calls. Body stubs are unreachable.
 *
 * Phase-1 I/O is synchronous and panics on failure (no
 * `Result<T, IOException>` wiring yet). Use `File.exists` to
 * guard before reading where appropriate.
 */
package jux.std.io;

import jux.std.exceptions.UnsupportedOperationException;

public class File {
    /**
     * Read the entire file at `path` into a `String`, assuming
     * UTF-8 encoding.
     */
    public static String readText(String path) {
        throw new UnsupportedOperationException("intrinsic");
    }

    /**
     * Write `content` to the file at `path`, replacing any
     * existing contents.
     */
    public static void writeText(String path, String content) {
        throw new UnsupportedOperationException("intrinsic");
    }

    /**
     * Cheap existence probe.
     */
    public static bool exists(String path) {
        throw new UnsupportedOperationException("intrinsic");
    }
}
"###),
    ("time/Clock.jux", r###"/**
 * jux.std.time.Clock
 *
 * Static-method entry point for wall-clock and monotonic-clock
 * reads. Mirrors a subset of `java.time.Clock` combined with
 * the immediate readings that `System.currentTimeMillis()`
 * provides.
 *
 * **Implementation status.** `Clock.nowMs` is a compiler
 * primitive — the backend routes the call to the
 * `__jux_now_ms()` helper emitted into the runtime prelude
 * (which wraps `std::time::SystemTime::now()`).
 */
package jux.std.time;

import jux.std.exceptions.UnsupportedOperationException;

public class Clock {
    /**
     * Read the wall-clock time as milliseconds since the UNIX
     * epoch (1970-01-01T00:00:00Z).
     */
    public static long nowMs() {
        throw new UnsupportedOperationException("intrinsic");
    }
}
"###),
];
