//! Embedded `jux.std` sources — generated by inlining the former on-disk
//! `jux.std/` tree so the compiler is **self-contained** (no loose stdlib
//! folder must ship next to the binary). Each entry is
//! `(relative-path, source)`; [`crate::stdlib::load_std_sources`] turns them
//! into `SourceFile`s under a synthetic `jux.std/<path>` path so source-map
//! markers and diagnostics read the same as before. Regenerate by re-running
//! the inliner if the stdlib declarations change.

/// `(relative-path, source-text)` for every former `jux.std/*.jux` file.
pub const STDLIB_SOURCES: &[(&str, &str)] = &[
    ("collections/Iterable.jux", r###"/**
 * jux.std.collections.Iterable<T>
 *
 * Root of every collection in the Jux stdlib. Anything that can
 * be stepped through with `for (T x : it)` implements this
 * interface. Mirrors `java.lang.Iterable<T>`.
 *
 * Phase-1 model: a single `iterator()` method returns an
 * `Iterator<T>` handle. The for-each loop machinery in the
 * backend special-cases known concrete iterables (`Vec`,
 * `HashMap`'s `keys()` / `values()`) — implementing this
 * interface from user code is a contract assertion today;
 * runtime dispatch through the trait shape lands when the
 * dyn-dispatch story matures.
 */
package jux.std.collections;

public interface Iterable<T> {
    /**
     * Build a fresh cursor that walks every element of this
     * collection in its natural order.
     *
     * @return a new iterator starting before the first element.
     */
    Iterator<T> iterator();
}
"###),
    ("collections/Iterator.jux", r###"/**
 * jux.std.collections.Iterator<T>
 *
 * Cursor over an `Iterable<T>` — the CANONICAL iteration protocol
 * per `JUX-CORE-LIB-ADDENDUM.md` §K.5 / `JUX-MISSING-DEFS` §M.10.1:
 * a single `next()` that yields the next element, or `null` when
 * the sequence is exhausted. (The earlier Java-style
 * `hasNext()`/`next()` pair was replaced by this nullable-driven
 * shape; a for-each loop lowers to `while let` on it directly.)
 *
 * Typical use:
 *
 *     final Iterator<int> it = xs.iterator();
 *     var n = it.next();
 *     while (n != null) {
 *         // ... use n ...
 *         n = it.next();
 *     }
 */
package jux.std.collections;

public interface Iterator<T> {
    /**
     * Advance the cursor and yield the next element, or `null`
     * when the sequence is exhausted.
     */
    T? next();
}
"###),
    ("concurrent/Atomics.jux", r###"/**
 * jux.std.concurrent - atomic integers + memory orderings (§S.6.2).
 *
 * `AtomicInt` / `AtomicLong` are thread-safe shared counters with
 * C++20/Rust memory-ordering control. The no-order overloads use
 * SeqCst - the safe default; profile before opting down. Handles
 * have SHARE semantics: passing one into `spawn`/`Worker.spawn`
 * shares the same underlying cell (Arc-backed).
 *
 * **Implementation status.** Compiler primitives - lowered onto
 * `std::sync::atomic::AtomicIsize` / `AtomicI64` behind `Arc`.
 * Phase-1 defers `compareAndSwap` (its `CasResult<T>` type is not
 * yet specified) and `AtomicRef<T>`.
 */
package jux.std.concurrent;

import jux.std.exceptions.UnsupportedOperationException;

public enum MemoryOrder {
    Relaxed,
    Acquire,
    Release,
    AcqRel,
    SeqCst;
}

public class AtomicInt {
    /**
     * Construct with an initial value.
     */
    public AtomicInt(int initial) {}

    /** Read the value (SeqCst). */
    public int load() { throw new UnsupportedOperationException("intrinsic"); }

    /** Read the value with an explicit ordering. */
    public int load(MemoryOrder order) { throw new UnsupportedOperationException("intrinsic"); }

    /** Write `value` (SeqCst). */
    public void store(int value) { throw new UnsupportedOperationException("intrinsic"); }

    /** Write `value` with an explicit ordering. */
    public void store(int value, MemoryOrder order) { throw new UnsupportedOperationException("intrinsic"); }

    /** Add `delta`, returning the PREVIOUS value (SeqCst). */
    public int fetchAdd(int delta) { throw new UnsupportedOperationException("intrinsic"); }

    /** Add `delta` with an explicit ordering; returns the previous value. */
    public int fetchAdd(int delta, MemoryOrder order) { throw new UnsupportedOperationException("intrinsic"); }

    /** Subtract `delta`, returning the previous value (SeqCst). */
    public int fetchSub(int delta) { throw new UnsupportedOperationException("intrinsic"); }

    /** Subtract `delta` with an explicit ordering; returns the previous value. */
    public int fetchSub(int delta, MemoryOrder order) { throw new UnsupportedOperationException("intrinsic"); }

    /** Bitwise-AND with `mask`, returning the previous value (SeqCst). */
    public int fetchAnd(int mask) { throw new UnsupportedOperationException("intrinsic"); }

    /** Bitwise-AND with an explicit ordering; returns the previous value. */
    public int fetchAnd(int mask, MemoryOrder order) { throw new UnsupportedOperationException("intrinsic"); }

    /** Bitwise-OR with `mask`, returning the previous value (SeqCst). */
    public int fetchOr(int mask) { throw new UnsupportedOperationException("intrinsic"); }

    /** Bitwise-OR with an explicit ordering; returns the previous value. */
    public int fetchOr(int mask, MemoryOrder order) { throw new UnsupportedOperationException("intrinsic"); }

    /** Bitwise-XOR with `mask`, returning the previous value (SeqCst). */
    public int fetchXor(int mask) { throw new UnsupportedOperationException("intrinsic"); }

    /** Bitwise-XOR with an explicit ordering; returns the previous value. */
    public int fetchXor(int mask, MemoryOrder order) { throw new UnsupportedOperationException("intrinsic"); }
}

public class AtomicLong {
    /**
     * Construct with an initial value.
     */
    public AtomicLong(long initial) {}

    /** Read the value (SeqCst). */
    public long load() { throw new UnsupportedOperationException("intrinsic"); }

    /** Read the value with an explicit ordering. */
    public long load(MemoryOrder order) { throw new UnsupportedOperationException("intrinsic"); }

    /** Write `value` (SeqCst). */
    public void store(long value) { throw new UnsupportedOperationException("intrinsic"); }

    /** Write `value` with an explicit ordering. */
    public void store(long value, MemoryOrder order) { throw new UnsupportedOperationException("intrinsic"); }

    /** Add `delta`, returning the PREVIOUS value (SeqCst). */
    public long fetchAdd(long delta) { throw new UnsupportedOperationException("intrinsic"); }

    /** Add `delta` with an explicit ordering; returns the previous value. */
    public long fetchAdd(long delta, MemoryOrder order) { throw new UnsupportedOperationException("intrinsic"); }

    /** Subtract `delta`, returning the previous value (SeqCst). */
    public long fetchSub(long delta) { throw new UnsupportedOperationException("intrinsic"); }

    /** Subtract `delta` with an explicit ordering; returns the previous value. */
    public long fetchSub(long delta, MemoryOrder order) { throw new UnsupportedOperationException("intrinsic"); }

    /** Bitwise-AND with `mask`, returning the previous value (SeqCst). */
    public long fetchAnd(long mask) { throw new UnsupportedOperationException("intrinsic"); }

    /** Bitwise-AND with an explicit ordering; returns the previous value. */
    public long fetchAnd(long mask, MemoryOrder order) { throw new UnsupportedOperationException("intrinsic"); }

    /** Bitwise-OR with `mask`, returning the previous value (SeqCst). */
    public long fetchOr(long mask) { throw new UnsupportedOperationException("intrinsic"); }

    /** Bitwise-OR with an explicit ordering; returns the previous value. */
    public long fetchOr(long mask, MemoryOrder order) { throw new UnsupportedOperationException("intrinsic"); }

    /** Bitwise-XOR with `mask`, returning the previous value (SeqCst). */
    public long fetchXor(long mask) { throw new UnsupportedOperationException("intrinsic"); }

    /** Bitwise-XOR with an explicit ordering; returns the previous value. */
    public long fetchXor(long mask, MemoryOrder order) { throw new UnsupportedOperationException("intrinsic"); }
}
"###),
    ("concurrent/Worker.jux", r###"/**
 * jux.std.concurrent.Worker
 *
 * Entry point for true multi-core parallelism per
 * JUX-ASYNC-ADDENDUM §18.2. `Worker.spawn(closure)` runs the
 * closure on a fresh OS thread from the system pool and
 * returns a `Task<T>` (a Future yielding the closure's return
 * value).
 *
 * **Implementation status.** `Worker.spawn` is a compiler
 * primitive — the backend special-cases the call (closures
 * need a bare `move ||` shape that doesn't fit the generic
 * lambda emit path) and generates the `std::thread::spawn(...)`
 * plus `futures::channel::oneshot` plumbing in the prelude.
 *
 * Package name is `concurrent` (not `async`) because `async`
 * is a reserved keyword in Jux for async-function declarations.
 */
package jux.std.concurrent;

public class Worker {
}
"###),
    ("exceptions/ArithmeticException.jux", r###"/**
 * jux.std.exceptions.ArithmeticException
 *
 * Numeric overflow, divide-by-zero, modulo-by-zero. Mirrors
 * `java.lang.ArithmeticException`.
 */
package jux.std.exceptions;

public class ArithmeticException extends RuntimeException {
    /**
     * Construct an ArithmeticException with a message
     * describing the arithmetic failure.
     */
    public ArithmeticException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/ClassCastException.jux", r###"/**
 * jux.std.exceptions.ClassCastException
 *
 * Runtime cast that the value's actual type doesn't satisfy
 * (e.g. `(Cat) animal` where `animal` is a `Dog`). Mirrors
 * `java.lang.ClassCastException`.
 */
package jux.std.exceptions;

public class ClassCastException extends RuntimeException {
    /**
     * Construct a ClassCastException with a message describing
     * the source and target types.
     */
    public ClassCastException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/Error.jux", r###"/**
 * jux.std.exceptions.Error
 *
 * Unrecoverable failure — out-of-memory, stack overflow,
 * internal invariant violations. Distinct from `Exception` so
 * that `catch (Exception e)` doesn't swallow runtime
 * catastrophes. Mirrors `java.lang.Error`.
 */
package jux.std.exceptions;

public class Error extends Throwable {
    /**
     * Construct an Error with the given diagnostic message.
     */
    public Error(String message) {
        super(message);
    }
}
"###),
    ("exceptions/Exception.jux", r###"/**
 * jux.std.exceptions.Exception
 *
 * Recoverable error condition. The general parent of every
 * exception a Jux program normally catches. Mirrors
 * `java.lang.Exception`.
 *
 * Distinct from `Error` so `catch (Exception e)` doesn't
 * accidentally swallow unrecoverable failures.
 */
package jux.std.exceptions;

public class Exception extends Throwable {
    /**
     * Chained cause, boxed in a 0/1-element array. The array gives
     * the recursive `Exception -> Exception` link heap indirection —
     * a direct `Exception? cause` field would make the value type
     * infinitely sized. Read through `getCause()` — the `__` prefix
     * marks it compiler-internal (public only so the inlined
     * accessor copies in subclass packages can reach it).
     */
    public Exception[] __causeBox;

    /**
     * Exceptions suppressed while this one was in flight (§X.1.1) —
     * appended by `addSuppressed`, e.g. when a `finally` throws while
     * an exception is already unwinding. `__`-prefixed internal —
     * read through `getSuppressed()`.
     */
    public Exception[] __suppressed;

    /**
     * Construct an Exception with the given diagnostic message and
     * no cause.
     */
    public Exception(String message) {
        super(message);
        this.__causeBox = new Exception[]{};
        this.__suppressed = new Exception[]{};
    }

    /**
     * Construct an Exception with a message and the exception that
     * caused it (§X.1.1 / §X.2.3) — the wrap-and-rethrow form:
     * `throw new Exception("config load failed", e);`.
     * `cause` is nullable so callers may pass `null` when the root
     * cause is unknown at the call site.
     */
    public Exception(String message, Exception? cause) {
        super(message);
        if (cause != null) {
            this.__causeBox = new Exception[]{cause};
        } else {
            this.__causeBox = new Exception[]{};
        }
        this.__suppressed = new Exception[]{};
    }

    /**
     * The exception that caused this one, or `null` when this is the
     * root of the chain. Walk `getCause()` repeatedly to print a
     * full causal chain.
     */
    public Exception? getCause() {
        if (this.__causeBox.length == 0) {
            return null;
        }
        return this.__causeBox[0];
    }

    /**
     * Record an exception suppressed while this one was in flight
     * (§X.1.1). Used by cleanup paths that fail during unwinding.
     */
    public void addSuppressed(Exception e) {
        this.__suppressed.push(e);
    }

    /**
     * Every exception recorded via `addSuppressed`, in insertion
     * order (defensive copy). Empty when nothing was suppressed.
     */
    public Exception[] getSuppressed() {
        var out = new Exception[]{};
        for (var s : this.__suppressed) {
            out.push(s);
        }
        return out;
    }
}
"###),
    ("exceptions/FileNotFoundException.jux", r###"/**
 * jux.std.exceptions.FileNotFoundException
 *
 * Specialization of `IOException` for the "file doesn't
 * exist" case. Mirrors `java.io.FileNotFoundException`.
 */
package jux.std.exceptions;

public class FileNotFoundException extends IOException {
    /**
     * Construct a FileNotFoundException naming the missing
     * path.
     */
    public FileNotFoundException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/IllegalArgumentException.jux", r###"/**
 * jux.std.exceptions.IllegalArgumentException
 *
 * Argument value violated a method's precondition. Mirrors
 * `java.lang.IllegalArgumentException`.
 */
package jux.std.exceptions;

public class IllegalArgumentException extends RuntimeException {
    /**
     * Construct an IllegalArgumentException with a message
     * describing the precondition that was violated.
     */
    public IllegalArgumentException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/IllegalStateException.jux", r###"/**
 * jux.std.exceptions.IllegalStateException
 *
 * Receiver was in the wrong state for the requested operation
 * (e.g. `iterator.next()` after exhaustion, double-close on a
 * stream). Mirrors `java.lang.IllegalStateException`.
 */
package jux.std.exceptions;

public class IllegalStateException extends RuntimeException {
    /**
     * Construct an IllegalStateException describing the
     * invalid state.
     */
    public IllegalStateException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/IndexOutOfBoundsException.jux", r###"/**
 * jux.std.exceptions.IndexOutOfBoundsException
 *
 * Array / list / string index outside the valid `[0, length)`
 * range. Mirrors `java.lang.IndexOutOfBoundsException`.
 */
package jux.std.exceptions;

public class IndexOutOfBoundsException extends RuntimeException {
    /**
     * Construct an IndexOutOfBoundsException with the given
     * diagnostic message (typically including the offending
     * index and the valid range).
     */
    public IndexOutOfBoundsException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/IOException.jux", r###"/**
 * jux.std.exceptions.IOException
 *
 * I/O failure — file not found, permission denied, broken
 * pipe, socket reset. Mirrors `java.io.IOException` (Java
 * keeps it under `java.io`; we group it under
 * `jux.std.exceptions` so every error type lives in one
 * place).
 */
package jux.std.exceptions;

public class IOException extends Exception {
    /**
     * Construct an IOException describing the I/O failure
     * (path, system error message, etc.).
     */
    public IOException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/NoSuchElementException.jux", r###"/**
 * jux.std.exceptions.NoSuchElementException
 *
 * Iterator exhausted, or `Map.get` / `List.first` / `List.last`
 * called on a collection with no matching element. Mirrors
 * `java.util.NoSuchElementException` (Java puts it in
 * `java.util` because the iterator interface lives there; we
 * collapse the tree under `jux.std.exceptions`).
 */
package jux.std.exceptions;

public class NoSuchElementException extends RuntimeException {
    /**
     * Construct a NoSuchElementException with a message
     * naming the missing element / iteration state.
     */
    public NoSuchElementException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/NullPointerException.jux", r###"/**
 * jux.std.exceptions.NullPointerException
 *
 * Dereference of a `null` value. Mirrors
 * `java.lang.NullPointerException`. The compiler emits this
 * automatically for unchecked nullable unwraps in Phase-2;
 * Phase-1 lets the user throw it manually.
 */
package jux.std.exceptions;

public class NullPointerException extends RuntimeException {
    /**
     * Construct a NullPointerException with the given
     * diagnostic message.
     */
    public NullPointerException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/RuntimeException.jux", r###"/**
 * jux.std.exceptions.RuntimeException
 *
 * Unchecked exceptions — bugs that the program *could* catch
 * but usually shouldn't. Mirrors `java.lang.RuntimeException`.
 * Parent of `NullPointerException`,
 * `IndexOutOfBoundsException`, `IllegalArgumentException`,
 * `ArithmeticException`, etc.
 */
package jux.std.exceptions;

public class RuntimeException extends Exception {
    /**
     * Construct a RuntimeException with the given diagnostic
     * message.
     */
    public RuntimeException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/TimeoutException.jux", r###"/**
 * jux.std.exceptions.TimeoutException
 *
 * An operation exceeded its time budget — thrown by
 * `withTimeout(ms, f)` (JUX-ASYNC v2 section 18.1.9) when the work
 * doesn't settle before the timer.
 */
package jux.std.exceptions;

public class TimeoutException extends Exception {
    /**
     * Construct a TimeoutException describing what timed out.
     */
    public TimeoutException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/CancellationException.jux", r###"/**
 * jux.std.exceptions.CancellationException
 *
 * A task was cancelled while being awaited (JUX-ASYNC v2 section
 * 18.1.9). Phase-1 note: `task.cancel()` consumes the handle, so
 * awaiting a cancelled task is a compile-time move error rather
 * than this exception; the type exists for forward compatibility
 * and user-thrown cancellation signaling.
 */
package jux.std.exceptions;

public class CancellationException extends Exception {
    /**
     * Construct a CancellationException with a reason.
     */
    public CancellationException(String message) {
        super(message);
    }
}
"###),
    ("exceptions/Throwable.jux", r###"/**
 * jux.std.exceptions.Throwable
 *
 * Root of the exception hierarchy. Every value that can flow
 * through a `throw` statement extends `Throwable`. Mirrors
 * `java.lang.Throwable`.
 *
 * Phase-1 model: carries a message string. Cause chains and
 * stack traces land in a follow-up addendum.
 */
package jux.std.exceptions;

public class Throwable {
    /**
     * Human-readable description of the failure.
     */
    public String message;

    /**
     * Construct a Throwable with the given diagnostic message.
     *
     * @param message text shown in the default panic hook.
     */
    public Throwable(String message) {
        this.message = message;
    }

    /**
     * Java-style accessor for the failure message — equivalent to
     * reading the `message` field directly; both forms are supported
     * (`e.message` and `e.getMessage()`).
     */
    public String getMessage() {
        return this.message;
    }
}
"###),
    ("exceptions/UnsupportedOperationException.jux", r###"/**
 * jux.std.exceptions.UnsupportedOperationException
 *
 * Operation that isn't supported on this receiver — e.g.
 * calling a mutating method on an immutable view. Mirrors
 * `java.lang.UnsupportedOperationException`. Also used by
 * stdlib intrinsic stubs whose bodies the backend replaces.
 */
package jux.std.exceptions;

public class UnsupportedOperationException extends RuntimeException {
    /**
     * Construct an UnsupportedOperationException naming the
     * unsupported operation.
     */
    public UnsupportedOperationException(String message) {
        super(message);
    }
}
"###),
    ("io/File.jux", r###"/**
 * jux.std.io.File
 *
 * Static-method entry point for file I/O. Mirrors a subset of
 * Java's `java.nio.file.Files` (with the cleaner naming of
 * `java.io.File`'s utility methods).
 *
 * **Implementation status.** File's static methods are
 * compiler primitives — the backend recognizes
 * `File.readText`, `File.writeText`, `File.exists` and emits
 * the matching `std::fs::*` calls. Body stubs are unreachable.
 *
 * Phase-1 I/O is synchronous and panics on failure (no
 * `Result<T, IOException>` wiring yet). Use `File.exists` to
 * guard before reading where appropriate.
 */
package jux.std.io;

import jux.std.exceptions.UnsupportedOperationException;

public class File {
    /**
     * Read the entire file at `path` into a `String`, assuming
     * UTF-8 encoding.
     */
    public static String readText(String path) {
        throw new UnsupportedOperationException("intrinsic");
    }

    /**
     * Write `content` to the file at `path`, replacing any
     * existing contents.
     */
    public static void writeText(String path, String content) {
        throw new UnsupportedOperationException("intrinsic");
    }

    /**
     * Cheap existence probe.
     */
    public static bool exists(String path) {
        throw new UnsupportedOperationException("intrinsic");
    }

    /**
     * Append `content` to the file at `path`, creating it first
     * when it doesn't exist yet.
     */
    public static void appendText(String path, String content) {
        throw new UnsupportedOperationException("intrinsic");
    }

    /**
     * Read the file at `path` and split it into lines (UTF-8;
     * line terminators stripped).
     */
    public static String[] readLines(String path) {
        throw new UnsupportedOperationException("intrinsic");
    }

    /**
     * Delete the file at `path`.
     */
    public static void delete(String path) {
        throw new UnsupportedOperationException("intrinsic");
    }

    /**
     * List the entry NAMES (not full paths) inside the directory
     * at `path`, in OS order.
     */
    public static String[] listDir(String path) {
        throw new UnsupportedOperationException("intrinsic");
    }
}
"###),
    ("io/Path.jux", r###"/**
 * jux.std.io.Path
 *
 * Static path-string manipulation — join/parent/fileName/
 * extension plus the directory/file probes. Paths are plain
 * `String`s in Phase-1 (no wrapper type); the query forms return
 * `String?` (`null` when the component doesn't exist, e.g. the
 * parent of a root or the extension of `Makefile`).
 *
 * **Implementation status.** Compiler primitives — the backend
 * lowers each call onto `std::path::Path` operations.
 */
package jux.std.io;

import jux.std.exceptions.UnsupportedOperationException;

public class Path {
    /**
     * Join two path segments with the platform separator.
     */
    public static String join(String base, String child) {
        throw new UnsupportedOperationException("intrinsic");
    }

    /**
     * The directory containing `path`, or `null` when there is
     * none (root or a bare file name).
     */
    public static String? parent(String path) {
        throw new UnsupportedOperationException("intrinsic");
    }

    /**
     * The final component of `path`, or `null` when the path
     * ends in `..` or is a root.
     */
    public static String? fileName(String path) {
        throw new UnsupportedOperationException("intrinsic");
    }

    /**
     * The extension (without the dot), or `null` when there is
     * none.
     */
    public static String? extension(String path) {
        throw new UnsupportedOperationException("intrinsic");
    }

    /** True when `path` exists and is a directory. */
    public static bool isDir(String path) {
        throw new UnsupportedOperationException("intrinsic");
    }

    /** True when `path` exists and is a regular file. */
    public static bool isFile(String path) {
        throw new UnsupportedOperationException("intrinsic");
    }
}
"###),
    ("meta/AnnotatedItem.jux", r###"/**
 * jux.std.meta.AnnotatedItem
 *
 * One entry in the compile-time annotation registry: a declaration that
 * carried a `RUNTIME`-retention annotation, and the values it was given.
 *
 * Jux has no runtime reflection, and this stands in its place. The compiler
 * walks every declaration at build time and generates `jux.meta.Registry`
 * holding one of these per application, so a framework can ask "what carries
 * @Route?" at startup without the program paying for a reflection system it
 * may not use. A project with no annotations generates an empty registry.
 *
 * Values are kept as text. An annotation's arguments are compile-time
 * constants, so their spelling is all there is to preserve, and the typed
 * getters convert on demand.
 */
package jux.std.meta;

public class AnnotatedItem {
    private String label;
    private String kind;
    private String owner;
    private String target;

    // Parallel lists rather than a map: an annotation has a handful of
    // parameters, so a linear scan is faster than hashing and pulls no
    // dependency into the stdlib. An ARRAY-valued parameter appears once per
    // element, which is what lets `list` return them without the compiler
    // having to pick a separator no value could contain.
    private Vec<String> keys;
    private Vec<String> values;

    public AnnotatedItem(String label, String kind, String owner, String target,
                         Vec<String> keys, Vec<String> values) {
        this.label = label;
        this.kind = kind;
        this.owner = owner;
        this.target = target;
        this.keys = keys;
        this.values = values;
    }

    /** The annotation's bare name, as declared -- `Route`, `Service`. */
    public String name() { return this.label; }

    /** What was annotated: `class`, `method`, `field`, or `function`. */
    public String kind() { return this.kind; }

    /**
     * The enclosing type's name for a member, or the empty string for a
     * top-level declaration.
     */
    public String owner() { return this.owner; }

    /** The annotated declaration's own name. */
    public String target() { return this.target; }

    /**
     * The value given for `key`, or null when the annotation has no such
     * parameter. A parameter left to its default is recorded with that
     * default, so a reader never has to know which were written out.
     */
    public String? get(String key) {
        for (int i = 0; i < this.keys.len(); i++) {
            if (this.keys[i] == key) {
                return this.values[i];
            }
        }
        return null;
    }

    /** `get` with a fallback, for the common "read it or use mine" shape. */
    public String getOr(String key, String fallback) {
        var found = this.get(key);
        return found == null ? fallback : found!!;
    }

    /** `get` parsed as an integer, or `fallback` when absent or unparsable. */
    public int getInt(String key, int fallback) {
        var raw = this.get(key);
        if (raw == null) {
            return fallback;
        }
        var text = raw!!;
        if (text.length() == 0) {
            return fallback;
        }
        bool negative = text.substring(0, 1) == "-";
        int start = negative ? 1 : 0;
        if (start >= text.length()) {
            return fallback;
        }
        int value = 0;
        for (int i = start; i < text.length(); i++) {
            int digit = "0123456789".indexOf(text.substring(i, i + 1));
            if (digit < 0) {
                return fallback;
            }
            value = value * 10 + digit;
        }
        return negative ? -value : value;
    }

    /** `get` read as a boolean, or `fallback` when absent. */
    public bool getBool(String key, bool fallback) {
        var raw = this.get(key);
        if (raw == null) {
            return fallback;
        }
        return raw!! == "true";
    }

    /**
     * Every value recorded for `key`, in order.
     *
     * An array-valued parameter is recorded once per element, so this returns
     * the elements; a single-valued one returns a list of one, and an absent
     * parameter an empty list.
     */
    public Vec<String> list(String key) {
        var out = new Vec<String>();
        for (int i = 0; i < this.keys.len(); i++) {
            if (this.keys[i] == key) {
                out.push(this.values[i]);
            }
        }
        return out;
    }

    public String string() {
        return "@" + this.label + " on " + this.kind + " " + this.target;
    }
}
"###),
    ("io/Console.jux", r###"/**
 * jux.std.io.Console
 *
 * Standard-input access. `print` covers stdout; this class adds
 * the read side. Mirrors the useful subset of Java's
 * `java.io.Console` / `Scanner` pair with Jux's nullable
 * protocol: `readLine()` returns `null` on end-of-input instead
 * of throwing.
 *
 * **Implementation status.** Compiler primitive — the backend
 * lowers `readLine` onto `std::io::stdin().read_line(..)`.
 */
package jux.std.io;

import jux.std.exceptions.UnsupportedOperationException;

public class Console {
    /**
     * Read one line from standard input, without the trailing
     * newline. Returns `null` at end-of-input (EOF / closed
     * pipe).
     */
    public static String? readLine() {
        throw new UnsupportedOperationException("intrinsic");
    }
}
"###),
    ("option/Option.jux", r###"/**
 * jux.std.option.Option
 *
 * Explicitly-typed optional value (§K.3) - `Some(T)` or `None`.
 * Distinct from the `T?` nullable syntax (the two do not implicitly
 * interconvert); use Option when a generic signature wants a named
 * type. Phase-1 surface: construction via the variant forms
 * (`Option.Some(v)` / `Option.None`) plus the query/unwrap methods
 * below; lambda combinators (map/flatMap) land with the
 * function-typed-parameter work.
 */
package jux.std.option;

public enum Option<T> {
    Some(T),
    None;

    /**
     * True when this Option holds a value.
     */
    public bool isSome() {
        return switch (this) {
            case Option.Some(var v) -> true;
            case Option.None -> false;
        };
    }

    /**
     * True when this Option is empty.
     */
    public bool isNone() {
        return !this.isSome();
    }

    /**
     * The held value; throws IllegalStateException on None.
     */
    public T unwrap() {
        return switch (this) {
            case Option.Some(var v) -> v;
            case Option.None -> {
                throw new IllegalStateException("unwrap on None");
            }
        };
    }

    /**
     * The held value, or `fallback` when None.
     */
    public T unwrapOr(T fallback) {
        return switch (this) {
            case Option.Some(var v) -> v;
            case Option.None -> fallback;
        };
    }
}
"###),
    ("result/Result.jux", r###"/**
 * jux.std.result.Result
 *
 * Success-or-error value (§K.4 / §X.4) - `Ok(T)` or `Err(E)`. The
 * `?` postfix propagates: `Ok(v)` unwraps to `v`, `Err(e)` returns
 * `Err(e)` from the enclosing function (whose return type must be a
 * Result with a compatible error type, E0730). Phase-1 surface:
 * construction via the variant forms (`Result.Ok(v)` /
 * `Result.Err(e)`) plus the query/unwrap methods; lambda combinators
 * (map/mapErr/flatMap) land with the function-typed-parameter work.
 */
package jux.std.result;

public enum Result<T, E> {
    Ok(T),
    Err(E);

    /**
     * True when this Result holds a success value.
     */
    public bool isOk() {
        return switch (this) {
            case Result.Ok(var v) -> true;
            case Result.Err(var e) -> false;
        };
    }

    /**
     * True when this Result holds an error.
     */
    public bool isErr() {
        return !this.isOk();
    }

    /**
     * The success value; throws IllegalStateException on Err.
     */
    public T unwrap() {
        return switch (this) {
            case Result.Ok(var v) -> v;
            case Result.Err(var e) -> {
                throw new IllegalStateException("unwrap on Err");
            }
        };
    }

    /**
     * The success value, or `fallback` when Err.
     */
    public T unwrapOr(T fallback) {
        return switch (this) {
            case Result.Ok(var v) -> v;
            case Result.Err(var e) -> fallback;
        };
    }
}
"###),
    ("time/Clock.jux", r###"/**
 * jux.std.time.Clock
 *
 * Static-method entry point for wall-clock and monotonic-clock
 * reads. Mirrors a subset of `java.time.Clock` combined with
 * the immediate readings that `System.currentTimeMillis()`
 * provides.
 *
 * **Implementation status.** `Clock.nowMs` is a compiler
 * primitive — the backend routes the call to the
 * `__jux_now_ms()` helper emitted into the runtime prelude
 * (which wraps `std::time::SystemTime::now()`).
 */
package jux.std.time;

import jux.std.exceptions.UnsupportedOperationException;

public class Clock {
    /**
     * Read the wall-clock time as milliseconds since the UNIX
     * epoch (1970-01-01T00:00:00Z).
     */
    public static long nowMs() {
        throw new UnsupportedOperationException("intrinsic");
    }
}
"###),
    ("time/Instant.jux", r###"/**
 * jux.std.time.Instant
 *
 * A point on the MONOTONIC clock - made for measuring elapsed
 * time (never jumps backward when the wall clock is adjusted).
 * Take one with `Instant.now()`, read the distance from it with
 * the `elapsed*` methods. For wall-clock time use `Clock.nowMs()`.
 *
 * **Implementation status.** Compiler primitive - lowers onto
 * Rust's `std::time::Instant`.
 */
package jux.std.time;

import jux.std.exceptions.UnsupportedOperationException;

public class Instant {
    /**
     * Capture the current monotonic instant.
     */
    public static Instant now() {
        throw new UnsupportedOperationException("intrinsic");
    }

    /**
     * Milliseconds elapsed since this instant was captured.
     */
    public long elapsedMs() {
        throw new UnsupportedOperationException("intrinsic");
    }

    /**
     * Nanoseconds elapsed since this instant was captured.
     */
    public long elapsedNanos() {
        throw new UnsupportedOperationException("intrinsic");
    }
}
"###),
    ("testing/Assertions.jux", r###"/**
 * jux.std.testing — the assertion surface of the testing framework
 * (JUX-TESTING-ADDENDUM §TS.3).
 *
 * Pure-Jux free functions. A failed assertion raises an assertion
 * FAILURE — a runtime panic carrying the message (§TS.4) — which no
 * `catch (Exception e)` in the code under test can swallow; the test
 * runner's boundary reports it as the test's FAIL message. Under
 * `jux test` the underlying `assert` builtin is always checked
 * (release builds included).
 */
package jux.std.testing;

/**
 * Assert two values are equal via the type's `operator==`. The message
 * renders both sides through `operator string`. Floats compare
 * EXACTLY — use `assertNear` for approximate comparison.
 */
public void assertEqual<T>(T expected, T actual)
        where T has operator==(T) -> bool, T has operator string() -> String {
    if (expected != actual) {
        assert(false, "assertEqual: expected `" + expected + "`, got `" + actual + "`");
    }
}

/**
 * Assert two values are NOT equal via the type's `operator==`.
 */
public void assertNotEqual<T>(T unexpected, T actual)
        where T has operator==(T) -> bool, T has operator string() -> String {
    if (unexpected == actual) {
        assert(false, "assertNotEqual: both sides are `" + actual + "`");
    }
}

/**
 * Assert a condition holds, with an optional message.
 */
public void assertTrue(bool condition, String message = "assertTrue failed") {
    if (!condition) {
        assert(false, message);
    }
}

/**
 * Assert a condition does NOT hold, with an optional message.
 */
public void assertFalse(bool condition, String message = "assertFalse failed") {
    if (condition) {
        assert(false, message);
    }
}

/**
 * Assert a nullable value is null.
 */
public void assertNull<T>(T? value) {
    if (value != null) {
        assert(false, "assertNull: value was non-null");
    }
}

/**
 * Assert a nullable value is non-null.
 */
public void assertNotNull<T>(T? value) {
    if (value == null) {
        assert(false, "assertNotNull: value was null");
    }
}

/**
 * Assert two doubles are within `epsilon` of each other — the
 * sanctioned float comparison (`assertEqual` on doubles is exact).
 */
public void assertNear(double expected, double actual, double epsilon = 0.000000001) {
    var diff = expected - actual;
    if (diff < 0.0) {
        diff = -diff;
    }
    if (diff > epsilon) {
        assert(false, "assertNear: expected `" + expected + "`, got `" + actual + "` (epsilon " + epsilon + ")");
    }
}

/**
 * Run `f` and assert it THROWS. Returns the caught exception for
 * inspection (`e.getMessage()`, type tests). Fails when `f` completes
 * normally. Phase-1 form of the spec's typed assertThrows — see
 * §TS.3 for the divergence note.
 */
public Exception assertThrows(() -> void action) {
    try {
        action();
    } catch (Exception e) {
        return e;
    }
    assert(false, "assertThrows: no exception was thrown");
    throw new RuntimeException("unreachable");
}
"###),
];
