// AUTO-GENERATED by juxc. DO NOT EDIT.
// Source: <jux compilation unit>

#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_imports)]
#![allow(unused_mut)]
#![allow(unused_parens)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(clippy::all)]
#![allow(arithmetic_overflow)]
#![deny(unconditional_recursion)]

pub mod __jux_rt {
    pub struct JuxShow<T>(pub T);
    pub trait JuxShowViaDisplay {
        fn jux_show(self) -> String;
    }
    impl<T: std::fmt::Display> JuxShowViaDisplay for &&JuxShow<T> {
        fn jux_show(self) -> String {
            jux_display_text(&self.0)
        }
    }
    pub fn jux_display_text<T: std::fmt::Display + ?Sized>(v: &T) -> String {
        let text = format!("{}", v);
        match std::any::type_name_of_val(v).trim_start_matches('&') {
            "f64" => text.parse::<f64>().map(crate::jux_float).unwrap_or(text),
            "f32" => text.parse::<f32>().map(crate::jux_float).unwrap_or(text),
            _ => text,
        }
    }
    pub trait JuxShowViaDebug {
        fn jux_show(self) -> String;
    }
    impl<T: std::fmt::Debug> JuxShowViaDebug for &JuxShow<T> {
        fn jux_show(self) -> String {
            jux_debug_text(&self.0)
        }
    }
    pub fn jux_debug_text<T: std::fmt::Debug + ?Sized>(v: &T) -> String {
        let text = format!("{:?}", v);
        let name = std::any::type_name_of_val(v).trim_start_matches('&');
        let quoted = matches!(name, "alloc::string::String" | "str" | "char")
            && text.len() >= 2
            && (text.starts_with('"') || text.starts_with('\''));
        if quoted {
            jux_unescape_debug(&text[1..text.len() - 1])
        } else {
            text
        }
    }
    /// Undo `escape_debug` on the text between a `Debug` string's quotes.
    fn jux_unescape_debug(inner: &str) -> String {
        let mut out = String::with_capacity(inner.len());
        let mut chars = inner.chars();
        while let Some(c) = chars.next() {
            if c != '\\' {
                out.push(c);
                continue;
            }
            match chars.next() {
                Some('n') => out.push('\n'),
                Some('r') => out.push('\r'),
                Some('t') => out.push('\t'),
                Some('0') => out.push('\0'),
                Some('u') => {
                    let code: String = chars.by_ref().skip(1).take_while(|c| *c != '}').collect();
                    if let Some(ch) = u32::from_str_radix(&code, 16).ok().and_then(char::from_u32) {
                        out.push(ch);
                    }
                }
                Some(other) => out.push(other),
                None => {}
            }
        }
        out
    }
    #[macro_export]
    macro_rules! __jux_show {
        ($v:expr) => {{
            #[allow(unused_imports)]
            use $crate::{JuxShowViaDebug as _, JuxShowViaDisplay as _};
            (&&$crate::JuxShow(&$v)).jux_show()
        }};
    }

    /// Render a floating-point value the way Jux prints one (LANG-V1 3.4),
    /// which is Java's `Double.toString` / `Float.toString`.
    pub trait JuxFloatText {
        fn jux_float_text(&self) -> String;
    }
    impl<T: JuxFloatText + ?Sized> JuxFloatText for &T {
        fn jux_float_text(&self) -> String {
            (**self).jux_float_text()
        }
    }
    pub fn jux_float<T: JuxFloatText>(v: T) -> String {
        v.jux_float_text()
    }
    macro_rules! jux_float_text_impl {
        ($t:ty) => {
            impl JuxFloatText for $t {
                fn jux_float_text(&self) -> String {
                    let v = *self;
                    let sign = if v.is_sign_negative() { "-" } else { "" };
                    let a = v.abs();
                    if v.is_nan() {
                        String::from("NaN")
                    } else if v.is_infinite() {
                        format!("{sign}Infinity")
                    } else if a == 0.0 {
                        format!("{sign}0.0")
                    } else {
                        // The shortest digits that read back as the value.
                        let (mut digits, mut exp) = jux_float_split(&format!("{:e}", a));
                        // Java writes at least two significant digits, and when one
                        // would do it takes the two-digit decimal nearest the exact
                        // value: `4.9E-324`, not `5.0E-324`, for the smallest subnormal.
                        if digits.len() == 1 {
                            (digits, exp) = jux_float_split(&format!("{:.1e}", a));
                        }
                        // Of two shortest decimals equally near the exact value, Java
                        // takes the one whose last digit is even.
                        let n = digits.len();
                        let last = digits.as_bytes()[n - 1] - b'0';
                        if n > 1 && last % 2 == 1 {
                            let exact = jux_float_split(&format!("{:.800e}", a as f64)).0;
                            for other in [last - 1, last + 1] {
                                let mut cand = digits[..n - 1].to_owned();
                                cand.push((b'0' + other.min(9)) as char);
                                let text = format!("{}.{}e{}", &cand[..1], &cand[1..], exp);
                                let tie = other <= 9
                                    && text.parse::<$t>().ok() == Some(a)
                                    && exact.len() > n
                                    && exact[..n - 1] == digits[..n - 1]
                                    && exact.as_bytes()[n - 1] - b'0' == last.min(other)
                                    && exact.as_bytes()[n] == b'5'
                                    && exact[n + 1..].bytes().all(|b| b == b'0');
                                if tie {
                                    digits = cand;
                                    break;
                                }
                            }
                        }
                        jux_float_layout(sign, digits, exp)
                    }
                }
            }
        };
    }
    jux_float_text_impl!(f64);
    jux_float_text_impl!(f32);
    /// `1.2345e21` as its significant digits (`"12345"`, trailing zeros
    /// dropped) and its exponent (`21`).
    fn jux_float_split(sci: &str) -> (String, i32) {
        let (mantissa, exp) = sci.split_once('e').unwrap_or((sci, "0"));
        let mut digits: String = mantissa.chars().filter(|c| *c != '.').collect();
        while digits.len() > 1 && digits.ends_with('0') {
            digits.pop();
        }
        (digits, exp.parse().unwrap_or(0))
    }
    /// Java's layout: plain decimal for 1e-3 <= |v| < 1e7, `d.dddE<exp>`
    /// otherwise, and always at least one digit after the point.
    fn jux_float_layout(sign: &str, digits: String, exp: i32) -> String {
        if (-3..7).contains(&exp) {
            if exp >= 0 {
                let int_len = exp as usize + 1;
                let mut int_part = digits.clone();
                while int_part.len() < int_len {
                    int_part.push('0');
                }
                let frac = if digits.len() > int_len {
                    &digits[int_len..]
                } else {
                    "0"
                };
                format!("{sign}{}.{frac}", &int_part[..int_len])
            } else {
                format!("{sign}0.{}{digits}", "0".repeat((-exp - 1) as usize))
            }
        } else {
            let frac = if digits.len() > 1 { &digits[1..] } else { "0" };
            format!("{sign}{}.{frac}E{exp}", &digits[..1])
        }
    }
    /// `a <=> b` on floats (Semantics 2.3): IEEE total order, except that
    /// every NaN is one value sorting after `+Infinity`, whatever its sign
    /// bit. `0.0 / 0.0` yields a NaN with the sign bit set on x86, which
    /// `total_cmp` alone sorts first.
    pub fn jux_fcmp(a: f64, b: f64) -> isize {
        match (a.is_nan(), b.is_nan()) {
            (true, true) => 0,
            (true, false) => 1,
            (false, true) => -1,
            (false, false) => a.total_cmp(&b) as isize,
        }
    }
    /// The cell inside a Jux array or collection handle.
    ///
    /// A plain `RefCell` would hold the value just as well, but its `Debug`
    /// prints the machinery: a program that says `print(v)` on a list of lists
    /// would see `RefCell { value: [1, 2] }` for every inner one. Printing a
    /// handle means printing what it holds, so `Debug` delegates -- and because
    /// it delegates, a NESTED handle formats correctly too, which no amount of
    /// borrowing at the print site can achieve.
    pub struct JuxCell<T: ?Sized>(pub std::cell::RefCell<T>);
    impl<T: ?Sized> std::ops::Deref for JuxCell<T> {
        type Target = std::cell::RefCell<T>;
        fn deref(&self) -> &Self::Target {
            &self.0
        }
    }
    impl<T: ?Sized + std::fmt::Debug> std::fmt::Debug for JuxCell<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            // `try_borrow` rather than `borrow`: a structure that reaches
            // itself, or one printed from inside a mutation, must not turn a
            // print into a panic.
            match self.0.try_borrow() {
                Ok(v) => std::fmt::Debug::fmt(&*v, f),
                Err(_) => f.write_str("<in use>"),
            }
        }
    }
    impl<T: ?Sized + std::fmt::Display> std::fmt::Display for JuxCell<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            match self.0.try_borrow() {
                Ok(v) => std::fmt::Display::fmt(&*v, f),
                Err(_) => f.write_str("<in use>"),
            }
        }
    }
    impl<T: Default> Default for JuxCell<T> {
        fn default() -> Self {
            JuxCell(std::cell::RefCell::new(T::default()))
        }
    }
    impl<T: ?Sized + PartialEq> PartialEq for JuxCell<T> {
        fn eq(&self, other: &Self) -> bool {
            *self.0.borrow() == *other.0.borrow()
        }
    }
    /// A Jux array: a shared, interior-mutable sequence.
    /// An async lambda's body, boxed as the future an `() async -> R`
    /// value produces when called (LANG-V1 §10.1.5).
    pub fn jux_async<F: std::future::Future + 'static>(
        f: F,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = F::Output>>> {
        Box::pin(f)
    }
    pub type JuxArr<T> = std::rc::Rc<JuxCell<T>>;
    /// Build a [`JuxArr`] - the constructor an alias cannot provide.
    pub fn jux_arr<T>(v: T) -> JuxArr<T> {
        std::rc::Rc::new(JuxCell(std::cell::RefCell::new(v)))
    }

    pub struct JuxSync<T: ?Sized>(pub std::sync::Arc<std::sync::Mutex<T>>);
    impl<T> JuxSync<T> {
        pub fn new(value: T) -> Self {
            JuxSync(std::sync::Arc::new(std::sync::Mutex::new(value)))
        }
    }
    impl<T: ?Sized> JuxSync<T> {
        pub fn borrow(&self) -> std::sync::MutexGuard<'_, T> {
            self.0.lock().unwrap_or_else(|e| e.into_inner())
        }
        pub fn borrow_mut(&self) -> std::sync::MutexGuard<'_, T> {
            self.borrow()
        }
        pub fn as_ptr(&self) -> *const std::sync::Mutex<T> {
            std::sync::Arc::as_ptr(&self.0)
        }
        pub fn ptr_eq(&self, other: &Self) -> bool {
            std::sync::Arc::ptr_eq(&self.0, &other.0)
        }
    }
    impl<T: ?Sized> Clone for JuxSync<T> {
        fn clone(&self) -> Self {
            JuxSync(self.0.clone())
        }
    }
    impl<T: ?Sized + std::fmt::Debug> std::fmt::Debug for JuxSync<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            std::fmt::Debug::fmt(&*self.borrow(), f)
        }
    }

    pub enum JuxObserver<F: ?Sized> {
        Weak(std::rc::Weak<F>),
        Strong(std::rc::Rc<F>),
        // A Strong ADAPTER whose real observer lives elsewhere
        // behind a weak ref (the §P.2.2 shape-2 wrapper): the
        // dead flag flips when the adapter detects its inner
        // observer died, so the fire loop prunes it (P5).
        StrongGuarded(std::rc::Rc<F>, std::rc::Rc<std::cell::Cell<bool>>),
    }
    impl<F: ?Sized> JuxObserver<F> {
        pub fn upgrade(&self) -> Option<std::rc::Rc<F>> {
            match self {
                JuxObserver::Weak(w) => w.upgrade(),
                JuxObserver::Strong(s) => Some(s.clone()),
                JuxObserver::StrongGuarded(s, dead) => {
                    if dead.get() {
                        None
                    } else {
                        Some(s.clone())
                    }
                }
            }
        }
        pub fn is_for(&self, target: &std::rc::Rc<F>) -> bool {
            self.upgrade()
                .map_or(false, |f| std::rc::Rc::ptr_eq(&f, target))
        }
    }
    impl<F: ?Sized> Clone for JuxObserver<F> {
        fn clone(&self) -> Self {
            match self {
                JuxObserver::Weak(w) => JuxObserver::Weak(w.clone()),
                JuxObserver::Strong(s) => JuxObserver::Strong(s.clone()),
                JuxObserver::StrongGuarded(s, d) => {
                    JuxObserver::StrongGuarded(s.clone(), d.clone())
                }
            }
        }
    }
    impl<F: ?Sized> std::fmt::Debug for JuxObserver<F> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str("observer")
        }
    }
    pub fn __jux_observer<F: ?Sized>(f: &std::rc::Rc<F>) -> JuxObserver<F> {
        if std::rc::Rc::strong_count(f) == 1 {
            JuxObserver::Strong(f.clone())
        } else {
            JuxObserver::Weak(std::rc::Rc::downgrade(f))
        }
    }

    pub fn __jux_order(o: crate::jux::std::concurrent::MemoryOrder) -> std::sync::atomic::Ordering {
        match o {
            crate::jux::std::concurrent::MemoryOrder::Relaxed => {
                std::sync::atomic::Ordering::Relaxed
            }
            crate::jux::std::concurrent::MemoryOrder::Acquire => {
                std::sync::atomic::Ordering::Acquire
            }
            crate::jux::std::concurrent::MemoryOrder::Release => {
                std::sync::atomic::Ordering::Release
            }
            crate::jux::std::concurrent::MemoryOrder::AcqRel => std::sync::atomic::Ordering::AcqRel,
            crate::jux::std::concurrent::MemoryOrder::SeqCst => std::sync::atomic::Ordering::SeqCst,
        }
    }

    pub trait JuxIntDiv {
        fn jux_div(self, rhs: Self) -> Self;
        fn jux_rem(self, rhs: Self) -> Self;
    }
    macro_rules! jux_int_div_impl {
    ($($t:ty),*) => {$(
        impl JuxIntDiv for $t {
            fn jux_div(self, rhs: Self) -> Self {
                if rhs == 0 {
                    std::panic::panic_any(crate::jux::std::exceptions::ArithmeticException::new(String::from("/ by zero")));
                }
                if cfg!(debug_assertions) { self / rhs } else { self.wrapping_div(rhs) }
            }
            fn jux_rem(self, rhs: Self) -> Self {
                if rhs == 0 {
                    std::panic::panic_any(crate::jux::std::exceptions::ArithmeticException::new(String::from("/ by zero")));
                }
                if cfg!(debug_assertions) { self % rhs } else { self.wrapping_rem(rhs) }
            }
        }
    )*};
}
    jux_int_div_impl!(i8, i16, i32, i64, i128, isize, u8, u16, u32, u64, u128, usize);
    pub fn __jux_idiv<T: JuxIntDiv>(a: T, b: T) -> T {
        a.jux_div(b)
    }
    pub fn __jux_irem<T: JuxIntDiv>(a: T, b: T) -> T {
        a.jux_rem(b)
    }

    pub fn __jux_upper(c: char) -> char {
        let mut up = c.to_uppercase();
        match (up.next(), up.next()) {
            (Some(u), None) => u,
            _ => c,
        }
    }
    pub fn __jux_lower(c: char) -> char {
        let mut low = c.to_lowercase();
        match (low.next(), low.next()) {
            (Some(l), None) => l,
            _ => c,
        }
    }

    /// A Rust `Err` thrown into Jux (Bindgen G.5.4). The error value rides
    /// along untouched for a `catch` that names its type; the text and type name
    /// serve `catch (Exception e)` and the uncaught-exception report.
    pub struct JuxForeignError {
        pub type_name: &'static str,
        pub text: String,
        pub error: ::std::boxed::Box<dyn ::std::any::Any + ::std::marker::Send>,
    }
    /// Throw the `Err` of a foreign call; `text` is its Display (or Debug) form.
    pub fn __jux_raise_foreign<E: ::std::any::Any + ::std::marker::Send>(
        text: String,
        error: E,
    ) -> ! {
        let type_name = ::std::any::type_name::<E>();
        let type_name = type_name.rsplit("::").next().unwrap_or(type_name);
        ::std::panic::panic_any(JuxForeignError {
            type_name,
            text,
            error: ::std::boxed::Box::new(error),
        })
    }
    /// For `catch (T e)` with `T` a foreign type: the Rust error itself, when it is a `T`.
    pub fn __jux_foreign_error_of<T: ::std::any::Any>(
        p: ::std::boxed::Box<dyn ::std::any::Any + ::std::marker::Send>,
    ) -> ::std::boxed::Box<dyn ::std::any::Any + ::std::marker::Send> {
        match p.downcast::<JuxForeignError>() {
            Ok(f) if f.error.is::<T>() => f.error,
            Ok(f) => f,
            Err(p) => p,
        }
    }
    /// For `catch (Exception e)`: a foreign error is an `Exception` carrying its text.
    pub fn __jux_foreign_as_exception(
        p: ::std::boxed::Box<dyn ::std::any::Any + ::std::marker::Send>,
    ) -> ::std::boxed::Box<dyn ::std::any::Any + ::std::marker::Send> {
        match p.downcast::<JuxForeignError>() {
            Ok(f) => ::std::boxed::Box::new(crate::jux::std::exceptions::Exception::new(f.text)),
            Err(p) => p,
        }
    }
    /// For `catch (Throwable e)`: the same, as a `Throwable`.
    pub fn __jux_foreign_as_throwable(
        p: ::std::boxed::Box<dyn ::std::any::Any + ::std::marker::Send>,
    ) -> ::std::boxed::Box<dyn ::std::any::Any + ::std::marker::Send> {
        match p.downcast::<JuxForeignError>() {
            Ok(f) => ::std::boxed::Box::new(crate::jux::std::exceptions::Throwable::new(f.text)),
            Err(p) => p,
        }
    }

    pub trait JuxIdentity {
        fn __jux_identity(&self) -> *const ();
    }
    impl<T: ?Sized + JuxIdentity> JuxIdentity for std::rc::Rc<T> {
        fn __jux_identity(&self) -> *const () {
            (**self).__jux_identity()
        }
    }
    impl<T: ?Sized + JuxIdentity> JuxIdentity for &T {
        fn __jux_identity(&self) -> *const () {
            (**self).__jux_identity()
        }
    }
    impl<T: ?Sized + JuxIdentity> JuxIdentity for ::std::boxed::Box<T> {
        fn __jux_identity(&self) -> *const () {
            (**self).__jux_identity()
        }
    }

    /// A Jux `any`: a value of any type (§T.1.2).
    #[derive(Clone)]
    pub struct JuxAny {
        value: ::std::rc::Rc<dyn ::std::any::Any>,
        /// The object's address, for a class instance, array or collection.
        address: Option<*const ()>,
        /// Value equality for everything else, `===` on a value type.
        same_value: fn(&dyn ::std::any::Any, &dyn ::std::any::Any) -> bool,
        text: ::std::rc::Rc<dyn Fn(&dyn ::std::any::Any) -> String>,
    }
    impl JuxAny {
        /// Hold a value type: `===` compares values.
        pub fn of_value<T: 'static + PartialEq>(value: T, text: fn(&T) -> String) -> JuxAny {
            fn same<T: 'static + PartialEq>(
                a: &dyn ::std::any::Any,
                b: &dyn ::std::any::Any,
            ) -> bool {
                matches!((a.downcast_ref::<T>(), b.downcast_ref::<T>()), (Some(a), Some(b)) if a == b)
            }
            JuxAny {
                value: ::std::rc::Rc::new(value),
                address: None,
                same_value: same::<T>,
                text: ::std::rc::Rc::new(move |v| {
                    text(v.downcast_ref::<T>().expect("the type it was built with"))
                }),
            }
        }
        /// Hold a class instance, array or collection: `===` compares addresses.
        pub fn of_ref<T: 'static + JuxIdentity>(value: T, text: fn(&T) -> String) -> JuxAny {
            fn never(_: &dyn ::std::any::Any, _: &dyn ::std::any::Any) -> bool {
                false
            }
            let address = Some(value.__jux_identity());
            JuxAny {
                value: ::std::rc::Rc::new(value),
                address,
                same_value: never,
                text: ::std::rc::Rc::new(move |v| {
                    text(v.downcast_ref::<T>().expect("the type it was built with"))
                }),
            }
        }
        /// Hold a value with no identity or equality Jux can read (a foreign
        /// value): it is `===` only to copies of this same `any`.
        pub fn of_opaque<T: 'static>(value: T, text: fn(&T) -> String) -> JuxAny {
            fn never(_: &dyn ::std::any::Any, _: &dyn ::std::any::Any) -> bool {
                false
            }
            let value: ::std::rc::Rc<dyn ::std::any::Any> = ::std::rc::Rc::new(value);
            let address = Some(::std::rc::Rc::as_ptr(&value).cast::<()>());
            JuxAny {
                value,
                address,
                same_value: never,
                text: ::std::rc::Rc::new(move |v| {
                    text(v.downcast_ref::<T>().expect("the type it was built with"))
                }),
            }
        }
        /// `a === b`.
        pub fn same(&self, other: &JuxAny) -> bool {
            // Two objects are the same when they are one object; two values when
            // they are equal values of one type; an object and a value never.
            match (self.address, other.address) {
                (Some(a), Some(b)) => a == b,
                (Option::None, Option::None) => (self.same_value)(&*self.value, &*other.value),
                _ => false,
            }
        }
        /// `v => T`, for the held value's own type.
        pub fn is<T: 'static>(&self) -> bool {
            self.value.is::<T>()
        }
        /// `v => T t`: the held value as a `T`, shared like any other read.
        pub fn get<T: 'static + Clone>(&self) -> Option<T> {
            self.value.downcast_ref::<T>().cloned()
        }
    }
    impl ::std::fmt::Display for JuxAny {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.write_str(&(self.text)(&*self.value))
        }
    }
    impl ::std::fmt::Debug for JuxAny {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.write_str(&(self.text)(&*self.value))
        }
    }
    /// A collection's identity is its shared cell.
    impl<T: ?Sized> JuxIdentity for ::std::cell::RefCell<T> {
        fn __jux_identity(&self) -> *const () {
            (self as *const Self).cast::<()>()
        }
    }
    /// An array's identity is its shared cell.
    impl<T: ?Sized> JuxIdentity for JuxCell<T> {
        fn __jux_identity(&self) -> *const () {
            (self as *const Self).cast::<()>()
        }
    }

    pub fn jux_hash<T: ::std::hash::Hash + ?Sized>(v: &T) -> isize {
        use ::std::hash::Hasher;
        let mut h = ::std::collections::hash_map::DefaultHasher::new();
        v.hash(&mut h);
        h.finish() as isize
    }
    pub fn jux_f64_bits(v: f64) -> u64 {
        if v == 0.0 {
            0
        } else if v.is_nan() {
            f64::NAN.to_bits()
        } else {
            v.to_bits()
        }
    }
    pub fn jux_f32_bits(v: f32) -> u32 {
        if v == 0.0 {
            0
        } else if v.is_nan() {
            f32::NAN.to_bits()
        } else {
            v.to_bits()
        }
    }
    pub fn jux_hash_f64(v: f64) -> isize {
        jux_hash(&jux_f64_bits(v))
    }
    pub fn jux_hash_f32(v: f32) -> isize {
        jux_hash(&jux_f32_bits(v))
    }
    pub fn jux_substring(s: &str, begin: isize, end: Option<isize>) -> String {
        let length = s.chars().count() as isize;
        let end = end.unwrap_or(length);
        if begin < 0 || end > length || begin > end {
            std::panic::panic_any(crate::jux::std::exceptions::IndexOutOfBoundsException::new(
                format!("Range [{begin}, {end}) out of bounds for length {length}"),
            ));
        }
        s.chars()
            .skip(begin as usize)
            .take((end - begin) as usize)
            .collect()
    }
    pub fn jux_substring_bytes(s: &str, begin: isize, end: isize) -> String {
        let length = s.len() as isize;
        if begin < 0 || end > length || begin > end {
            std::panic::panic_any(crate::jux::std::exceptions::IndexOutOfBoundsException::new(
                format!("Range [{begin}, {end}) out of bounds for length {length}"),
            ));
        }
        match s.get(begin as usize..end as usize) {
            Some(part) => part.to_owned(),
            None => std::panic::panic_any(crate::jux::std::exceptions::EncodingException::new(
                format!("Range [{begin}, {end}) splits a multi-byte character"),
            )),
        }
    }
    pub fn jux_char_at(s: &str, at: isize) -> char {
        match usize::try_from(at).ok().and_then(|i| s.chars().nth(i)) {
            Some(c) => c,
            None => {
                std::panic::panic_any(crate::jux::std::exceptions::IndexOutOfBoundsException::new(
                    format!("Index {at} out of bounds for length {}", s.chars().count()),
                ))
            }
        }
    }

    pub struct __JuxYieldNow(bool);
    impl std::future::Future for __JuxYieldNow {
        type Output = ();
        fn poll(
            mut self: std::pin::Pin<&mut Self>,
            cx: &mut std::task::Context<'_>,
        ) -> std::task::Poll<()> {
            if self.0 {
                std::task::Poll::Ready(())
            } else {
                self.0 = true;
                cx.waker().wake_by_ref();
                std::task::Poll::Pending
            }
        }
    }
    pub fn __jux_yield_now() -> __JuxYieldNow {
        __JuxYieldNow(false)
    }

    pub struct JuxTaskShared {
        // (orphaned, parked failure)
        state: std::sync::Mutex<(
            bool,
            Option<::std::boxed::Box<dyn ::std::any::Any + ::std::marker::Send>>,
        )>,
        // Set by `cancel()`: the task throws where it next resumes.
        cancelled: std::sync::atomic::AtomicBool,
    }
    thread_local! {
        static __JUX_CANCEL: std::cell::RefCell<Vec<std::sync::Arc<JuxTaskShared>>> =
            const { std::cell::RefCell::new(Vec::new()) };
    }
    /// A spawned task's future, with its cancellation flag in scope while it runs.
    pub struct JuxCancelScope<F> {
        inner: std::pin::Pin<::std::boxed::Box<F>>,
        shared: std::sync::Arc<JuxTaskShared>,
    }
    impl<F: std::future::Future> std::future::Future for JuxCancelScope<F> {
        type Output = F::Output;
        fn poll(
            mut self: std::pin::Pin<&mut Self>,
            cx: &mut std::task::Context<'_>,
        ) -> std::task::Poll<F::Output> {
            // A guard, so the flag leaves the stack even when the body unwinds.
            struct Pop;
            impl Drop for Pop {
                fn drop(&mut self) {
                    __JUX_CANCEL.with(|c| {
                        c.borrow_mut().pop();
                    });
                }
            }
            let me = self.as_mut().get_mut();
            __JUX_CANCEL.with(|c| c.borrow_mut().push(me.shared.clone()));
            let _pop = Pop;
            me.inner.as_mut().poll(cx)
        }
    }
    /// What an `await` resumed with, unless this task was cancelled meanwhile.
    pub fn __jux_awaited<T>(value: T) -> T {
        let cancelled = __JUX_CANCEL.with(|c| {
            c.borrow().last().map_or(false, |s| {
                s.cancelled.load(std::sync::atomic::Ordering::SeqCst)
            })
        });
        if cancelled {
            std::panic::panic_any(crate::jux::std::exceptions::CancellationException::new(
                String::from("task was cancelled"),
            ));
        }
        value
    }
    pub struct JuxTask<T>(
        std::cell::Cell<Option<futures::future::RemoteHandle<Result<T, ()>>>>,
        std::sync::Arc<JuxTaskShared>,
    );
    impl<T: 'static> JuxTask<T> {
        /// The awaiter's side of a failed task: rethrow what it threw.
        fn settle(shared: &JuxTaskShared, result: Result<T, ()>) -> T {
            match result {
                Ok(v) => v,
                Err(()) => {
                    let parked = shared
                        .state
                        .lock()
                        .unwrap_or_else(|e| e.into_inner())
                        .1
                        .take();
                    std::panic::resume_unwind(parked.expect("a failed task parks its exception"))
                }
            }
        }
        /// What awaiting a cancelled task gives: its CancellationException.
        fn cancelled() -> ! {
            std::panic::panic_any(crate::jux::std::exceptions::CancellationException::new(
                String::from("task was cancelled"),
            ))
        }
        #[allow(non_snake_case)]
        pub fn blockingGet(self) -> T {
            let Some(handle) = self.0.take() else {
                Self::cancelled()
            };
            Self::settle(&self.1, crate::__jux_block_on(handle))
        }
        pub fn cancel(&self) {
            // Cooperative, per EXCEPTIONS X.7.3: the task throws
            // CancellationException where it next resumes, so its finally
            // blocks and drops run. The handle stays, and awaiting it
            // afterwards re-throws what the task threw.
            self.1
                .cancelled
                .store(true, std::sync::atomic::Ordering::SeqCst);
        }
    }
    impl<T> Drop for JuxTask<T> {
        fn drop(&mut self) {
            if let Some(h) = self.0.get_mut().take() {
                h.forget();
                // Nobody will await it now: a failure already parked is
                // unhandled, and a later one will be reported by the task.
                let parked = {
                    let mut state = self.1.state.lock().unwrap_or_else(|e| e.into_inner());
                    state.0 = true;
                    state.1.take()
                };
                // A CANCELLED task reports nothing (ERRATA E92): the caller
                // said it no longer wants the result, so there is no
                // rejection left to be unhandled.
                let cancelled = self.1.cancelled.load(std::sync::atomic::Ordering::SeqCst);
                if let (Some(p), false) = (parked, cancelled) {
                    crate::__jux_unhandled_rejection(p);
                }
            }
        }
    }
    impl<T: 'static> std::future::Future for JuxTask<T> {
        type Output = T;
        fn poll(
            mut self: std::pin::Pin<&mut Self>,
            cx: &mut std::task::Context<'_>,
        ) -> std::task::Poll<T> {
            let Some(h) = self.0.get_mut().as_mut() else {
                Self::cancelled()
            };
            match std::pin::Pin::new(h).poll(cx) {
                std::task::Poll::Pending => std::task::Poll::Pending,
                std::task::Poll::Ready(result) => {
                    // Consumed: the handle's drop must not orphan the task.
                    *self.0.get_mut() = None;
                    std::task::Poll::Ready(Self::settle(&self.1, result))
                }
            }
        }
    }
    pub struct JuxLoop {
        pool: std::cell::RefCell<Option<futures::executor::LocalPool>>,
        spawner: futures::executor::LocalSpawner,
    }
    thread_local! {
        static __JUX_LOOP: JuxLoop = {
            let pool = futures::executor::LocalPool::new();
            let spawner = pool.spawner();
            JuxLoop { pool: std::cell::RefCell::new(Some(pool)), spawner }
        };
    }
    /// Drive `f` to completion, running the loop's other tasks meanwhile.
    pub fn __jux_block_on<F: std::future::Future>(f: F) -> F::Output {
        struct Restore(Option<futures::executor::LocalPool>);
        impl Drop for Restore {
            fn drop(&mut self) {
                if let Some(p) = self.0.take() {
                    __JUX_LOOP.with(|l| *l.pool.borrow_mut() = Some(p));
                }
            }
        }
        let mut held = Restore(__JUX_LOOP.with(|l| l.pool.borrow_mut().take()));
        match held.0.as_mut() {
            Some(pool) => pool.run_until(f),
            // Already inside the loop: this drive is nested, and runs the
            // future it was handed on the thread that is already here.
            None => futures::executor::block_on(f),
        }
    }
    pub struct JuxDelay {
        deadline: std::time::Instant,
        armed: bool,
    }
    impl std::future::Future for JuxDelay {
        type Output = ();
        fn poll(
            mut self: std::pin::Pin<&mut Self>,
            cx: &mut std::task::Context<'_>,
        ) -> std::task::Poll<()> {
            let now = std::time::Instant::now();
            if now >= self.deadline {
                std::task::Poll::Ready(())
            } else {
                if !self.armed {
                    self.armed = true;
                    let waker = cx.waker().clone();
                    let wait = self.deadline - now;
                    std::thread::spawn(move || {
                        std::thread::sleep(wait);
                        waker.wake();
                    });
                }
                std::task::Poll::Pending
            }
        }
    }
    impl JuxDelay {
        #[allow(non_snake_case)]
        pub fn blockingGet(self) {
            crate::__jux_block_on(self);
        }
    }
    pub fn __jux_delay(d: std::time::Duration) -> JuxDelay {
        JuxDelay {
            deadline: std::time::Instant::now() + d,
            armed: false,
        }
    }
    pub fn __jux_spawn<T: 'static>(
        fut: impl std::future::Future<Output = T> + 'static,
    ) -> JuxTask<T> {
        let shared = std::sync::Arc::new(JuxTaskShared {
            state: std::sync::Mutex::new((false, None)),
            cancelled: std::sync::atomic::AtomicBool::new(false),
        });
        let task_side = shared.clone();
        let guarded = async move {
            match futures::FutureExt::catch_unwind(std::panic::AssertUnwindSafe(fut)).await {
                Ok(v) => Ok(v),
                Err(p) => {
                    let orphaned = {
                        let mut state = task_side.state.lock().unwrap_or_else(|e| e.into_inner());
                        if state.0 {
                            Some(p)
                        } else {
                            state.1 = Some(p);
                            None
                        }
                    };
                    // A cancelled task reports nothing (ERRATA E92).
                    let quiet = task_side
                        .cancelled
                        .load(std::sync::atomic::Ordering::SeqCst);
                    if let (Some(p), false) = (orphaned, quiet) {
                        crate::__jux_unhandled_rejection(p);
                    }
                    Err(())
                }
            }
        };
        let scoped = JuxCancelScope {
            inner: ::std::boxed::Box::pin(guarded),
            shared: shared.clone(),
        };
        let handle = __JUX_LOOP.with(|l| {
            futures::task::LocalSpawnExt::spawn_local_with_handle(&l.spawner, scoped)
                .expect("spawn")
        });
        JuxTask(std::cell::Cell::new(Some(handle)), shared)
    }

    pub struct JuxChannelInner<T> {
        tx: std::sync::Mutex<Option<futures::channel::mpsc::Sender<T>>>,
        rx: futures::lock::Mutex<futures::channel::mpsc::Receiver<T>>,
    }
    pub struct JuxChannel<T> {
        inner: std::sync::Arc<JuxChannelInner<T>>,
    }
    impl<T> Clone for JuxChannel<T> {
        fn clone(&self) -> Self {
            JuxChannel {
                inner: self.inner.clone(),
            }
        }
    }
    impl<T> JuxChannel<T> {
        pub fn new(capacity: isize) -> Self {
            let (tx, rx) = futures::channel::mpsc::channel(capacity.max(1) as usize);
            JuxChannel {
                inner: std::sync::Arc::new(JuxChannelInner {
                    tx: std::sync::Mutex::new(Some(tx)),
                    rx: futures::lock::Mutex::new(rx),
                }),
            }
        }
        pub async fn send(&self, v: T) {
            let tx = self.inner.tx.lock().unwrap().clone();
            if let Some(mut tx) = tx {
                let _ = futures::sink::SinkExt::send(&mut tx, v).await;
            }
        }
        pub async fn receive(&self) -> Option<T> {
            let mut rx = self.inner.rx.lock().await;
            futures::stream::StreamExt::next(&mut *rx).await
        }
        pub fn close(&self) {
            *self.inner.tx.lock().unwrap() = None;
        }
    }

    pub struct JuxStream<T> {
        inner: std::rc::Rc<std::cell::RefCell<futures::stream::LocalBoxStream<'static, T>>>,
    }
    impl<T> Clone for JuxStream<T> {
        fn clone(&self) -> Self {
            JuxStream {
                inner: self.inner.clone(),
            }
        }
    }
    impl<T: Clone + 'static> JuxStream<T> {
        pub fn from_stream(s: futures::stream::LocalBoxStream<'static, T>) -> Self {
            // `fuse` makes exhaustion idempotent (§18.6.2): every
            // `next()` after the first None resolves None instead of
            // re-polling the source (`unfold` panics if re-polled).
            let fused = ::std::boxed::Box::pin(futures::stream::StreamExt::fuse(s));
            JuxStream {
                inner: std::rc::Rc::new(std::cell::RefCell::new(fused)),
            }
        }
        pub fn of(items: Vec<T>) -> Self {
            Self::from_stream(::std::boxed::Box::pin(futures::stream::iter(items)))
        }
        pub fn from(items: Vec<T>) -> Self {
            Self::of(items)
        }
        pub fn generate(
            f: impl FnMut() -> futures::future::LocalBoxFuture<'static, Option<T>> + 'static,
        ) -> Self {
            Self::from_stream(::std::boxed::Box::pin(futures::stream::unfold(
                f,
                |mut f| async move { f().await.map(|v| (v, f)) },
            )))
        }
        pub async fn next(&self) -> Option<T> {
            let mut s = self.inner.borrow_mut();
            futures::stream::StreamExt::next(&mut *s).await
        }
        pub fn take_inner(&self) -> futures::stream::LocalBoxStream<'static, T> {
            std::mem::replace(
                &mut *self.inner.borrow_mut(),
                ::std::boxed::Box::pin(futures::stream::empty()),
            )
        }
        #[allow(non_snake_case)]
        pub fn mapAsync<U: Clone + 'static>(&self, f: std::rc::Rc<dyn Fn(T) -> U>) -> JuxStream<U> {
            JuxStream::from_stream(::std::boxed::Box::pin(futures::stream::StreamExt::map(
                self.take_inner(),
                move |v| f(v),
            )))
        }
        #[allow(non_snake_case)]
        pub fn filterAsync(&self, f: std::rc::Rc<dyn Fn(T) -> bool>) -> JuxStream<T> {
            Self::from_stream(::std::boxed::Box::pin(futures::stream::StreamExt::filter(
                self.take_inner(),
                move |v: &T| futures::future::ready(f(v.clone())),
            )))
        }
        pub fn take(&self, n: isize) -> JuxStream<T> {
            Self::from_stream(::std::boxed::Box::pin(futures::stream::StreamExt::take(
                self.take_inner(),
                n.max(0) as usize,
            )))
        }
        pub fn skip(&self, n: isize) -> JuxStream<T> {
            Self::from_stream(::std::boxed::Box::pin(futures::stream::StreamExt::skip(
                self.take_inner(),
                n.max(0) as usize,
            )))
        }
        pub fn chain(&self, other: JuxStream<T>) -> JuxStream<T> {
            Self::from_stream(::std::boxed::Box::pin(futures::stream::StreamExt::chain(
                self.take_inner(),
                other.take_inner(),
            )))
        }
    }

    pub struct JuxYield<T>(std::rc::Rc<std::cell::Cell<Option<T>>>);
    impl<T> JuxYield<T> {
        /// Hand `value` to the consumer, then pause until it asks again.
        pub fn yield_(&self, value: T) -> JuxYieldPoint {
            self.0.set(Some(value));
            JuxYieldPoint(false)
        }
    }
    pub struct JuxYieldPoint(bool);
    impl std::future::Future for JuxYieldPoint {
        type Output = ();
        fn poll(
            mut self: std::pin::Pin<&mut Self>,
            _: &mut std::task::Context<'_>,
        ) -> std::task::Poll<()> {
            if self.0 {
                std::task::Poll::Ready(())
            } else {
                self.0 = true;
                std::task::Poll::Pending
            }
        }
    }
    pub struct JuxGenerator<T> {
        slot: std::rc::Rc<std::cell::Cell<Option<T>>>,
        body: std::cell::RefCell<
            Option<std::pin::Pin<::std::boxed::Box<dyn std::future::Future<Output = ()>>>>,
        >,
    }
    impl<T: 'static> JuxGenerator<T> {
        pub fn new<F: std::future::Future<Output = ()> + 'static>(
            body: impl FnOnce(JuxYield<T>) -> F,
        ) -> Self {
            let slot = std::rc::Rc::new(std::cell::Cell::new(Option::None));
            let body = body(JuxYield(slot.clone()));
            JuxGenerator {
                slot,
                body: std::cell::RefCell::new(Some(::std::boxed::Box::pin(body))),
            }
        }
        /// Run the body to its next `yield` or to its end.
        fn resume(&self, cx: &mut std::task::Context<'_>) -> std::task::Poll<Option<T>> {
            let mut body = self.body.borrow_mut();
            // A throw escaping the body ends the generator: the exception
            // reaches the consumer, and later `next()` calls answer null.
            // A finished generator reads as a body that just completed.
            let step = match body.as_mut() {
                Some(running) => std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                    running.as_mut().poll(cx)
                })),
                Option::None => Ok(std::task::Poll::Ready(())),
            };
            let step = match step {
                Ok(step) => step,
                Err(payload) => {
                    *body = None;
                    drop(body);
                    std::panic::resume_unwind(payload);
                }
            };
            match step {
                std::task::Poll::Ready(()) => {
                    *body = None;
                    std::task::Poll::Ready(Option::None)
                }
                std::task::Poll::Pending => match self.slot.take() {
                    Some(value) => std::task::Poll::Ready(Some(value)),
                    // An async generator waiting on something it awaited.
                    None => std::task::Poll::Pending,
                },
            }
        }
        pub fn next(&self) -> Option<T> {
            let mut cx = std::task::Context::from_waker(std::task::Waker::noop());
            match self.resume(&mut cx) {
                std::task::Poll::Ready(value) => value,
                std::task::Poll::Pending => unreachable!("a synchronous generator never awaits"),
            }
        }
    }
    impl<T> std::fmt::Debug for JuxGenerator<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str("generator")
        }
    }
    impl<T> std::fmt::Display for JuxGenerator<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str("generator")
        }
    }
    impl<T> JuxIdentity for JuxGenerator<T> {
        fn __jux_identity(&self) -> *const () {
            (self as *const Self).cast::<()>()
        }
    }
    impl<T: Clone + std::fmt::Debug + 'static> crate::jux::std::collections::Iterator<T>
        for JuxGenerator<T>
    {
        fn next(&self) -> Option<T> {
            JuxGenerator::next(self)
        }
    }
    impl<T: 'static> futures::stream::Stream for JuxGenerator<T> {
        type Item = T;
        fn poll_next(
            self: std::pin::Pin<&mut Self>,
            cx: &mut std::task::Context<'_>,
        ) -> std::task::Poll<Option<T>> {
            self.resume(cx)
        }
    }

    pub struct JuxAsyncMutex<T> {
        inner: std::sync::Arc<futures::lock::Mutex<T>>,
    }
    impl<T> Clone for JuxAsyncMutex<T> {
        fn clone(&self) -> Self {
            JuxAsyncMutex {
                inner: self.inner.clone(),
            }
        }
    }
    impl<T> JuxAsyncMutex<T> {
        pub fn new(v: T) -> Self {
            JuxAsyncMutex {
                inner: std::sync::Arc::new(futures::lock::Mutex::new(v)),
            }
        }
        pub async fn lock(&self) -> futures::lock::MutexGuard<'_, T> {
            self.inner.lock().await
        }
    }

    #[derive(Debug, Clone)]
    pub struct JuxStepped<T> {
        pub start: T,
        pub end: T,
        pub step: i64,
        inclusive: bool,
        next: Option<T>,
    }
    impl<T: Clone> JuxStepped<T> {
        pub fn new(start: T, end: T, step: i64, inclusive: bool) -> Self {
            JuxStepped {
                next: Some(start.clone()),
                start,
                end,
                step,
                inclusive,
            }
        }
    }
    impl<T: Clone + PartialOrd + TryFrom<i128> + TryInto<i128>> Iterator for JuxStepped<T> {
        type Item = T;
        fn next(&mut self) -> Option<T> {
            if self.step == 0 {
                std::panic::panic_any(crate::jux::std::exceptions::ArithmeticException::new(
                    String::from("range step is zero"),
                ));
            }
            let cur = self.next.take()?;
            let more = if self.step > 0 {
                if self.inclusive {
                    cur <= self.end
                } else {
                    cur < self.end
                }
            } else if self.inclusive {
                cur >= self.end
            } else {
                cur > self.end
            };
            // Past the end, or past the type's own range, the walk is over.
            more.then(|| {
                self.next = cur
                    .clone()
                    .try_into()
                    .ok()
                    .and_then(|c: i128| T::try_from(c + self.step as i128).ok());
                cur
            })
        }
    }

    pub struct JuxMutex<T> {
        inner: std::sync::Arc<std::sync::Mutex<T>>,
    }
    impl<T> Clone for JuxMutex<T> {
        fn clone(&self) -> Self {
            JuxMutex {
                inner: self.inner.clone(),
            }
        }
    }
    impl<T> std::fmt::Debug for JuxMutex<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str("Mutex")
        }
    }
    impl<T: Clone> JuxMutex<T> {
        pub fn new(v: T) -> Self {
            JuxMutex {
                inner: std::sync::Arc::new(std::sync::Mutex::new(v)),
            }
        }
        pub fn lock(&self, update: std::rc::Rc<dyn Fn(T) -> T>) -> T {
            let mut guard = self
                .inner
                .lock()
                .unwrap_or_else(|poisoned| poisoned.into_inner());
            let next = update((*guard).clone());
            *guard = next.clone();
            next
        }
    }

    pub struct Task<T>(futures::channel::oneshot::Receiver<T>);
    impl<T> std::future::Future for Task<T> {
        type Output = T;
        fn poll(
            mut self: std::pin::Pin<&mut Self>,
            cx: &mut std::task::Context<'_>,
        ) -> std::task::Poll<T> {
            match std::future::Future::poll(std::pin::Pin::new(&mut self.0), cx) {
                std::task::Poll::Ready(Ok(v)) => std::task::Poll::Ready(v),
                std::task::Poll::Ready(Err(_)) => panic!("worker task aborted before completion"),
                std::task::Poll::Pending => std::task::Poll::Pending,
            }
        }
    }
    impl<T> Task<T> {
        pub fn join(self) -> T {
            crate::__jux_block_on(self)
        }
    }
    pub struct Worker;
    impl Worker {
        pub fn spawn<T: Send + 'static, F: FnOnce() -> T + Send + 'static>(f: F) -> Task<T> {
            let (tx, rx) = futures::channel::oneshot::channel();
            std::thread::spawn(move || {
                let _ = tx.send(f());
            });
            Task(rx)
        }
    }
    pub fn __jux_now_ms() -> i64 {
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_millis() as i64)
            .unwrap_or(0)
    }
}
pub use __jux_rt::*;

// JUX:F:/DEV/juxlang/.claude/worktrees/agent-acc64c5fc6ee9d73d/examples/stress_sealed_pat.jux:3:8
#[derive(Clone, Debug)]
pub struct Light_Inner {}

#[derive(Clone, Debug)]
pub(crate) struct Light(pub(crate) std::rc::Rc<std::cell::RefCell<Light_Inner>>);

impl Light {
    pub fn new_inner() -> Light_Inner {
        Light_Inner {}
    }

    pub fn new() -> Self {
        Self(std::rc::Rc::new(std::cell::RefCell::new(Self::new_inner())))
    }
}

impl std::fmt::Display for Light {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Light@{:p}", std::rc::Rc::as_ptr(&self.0))
    }
}

impl crate::JuxIdentity for Light {
    fn __jux_identity(&self) -> *const () {
        std::rc::Rc::as_ptr(&self.0) as *const ()
    }
}

impl PartialEq for Light {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::eq(std::rc::Rc::as_ptr(&self.0), std::rc::Rc::as_ptr(&other.0))
    }
}
impl Eq for Light {}
impl std::hash::Hash for Light {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        std::ptr::hash(std::rc::Rc::as_ptr(&self.0), state)
    }
}

pub(crate) trait LightKind:
    std::fmt::Debug + std::fmt::Display + crate::JuxIdentity
{
    fn __jux_as_Green(&self) -> Option<Green> {
        None
    }
    fn __jux_as_Red(&self) -> Option<Red> {
        None
    }
    fn __jux_as_Yellow(&self) -> Option<Yellow> {
        None
    }
}
impl From<Green> for std::rc::Rc<dyn LightKind> {
    fn from(__v: Green) -> Self {
        std::rc::Rc::new(__v)
    }
}
impl From<Light> for std::rc::Rc<dyn LightKind> {
    fn from(__v: Light) -> Self {
        std::rc::Rc::new(__v)
    }
}
impl From<Red> for std::rc::Rc<dyn LightKind> {
    fn from(__v: Red) -> Self {
        std::rc::Rc::new(__v)
    }
}
impl From<Yellow> for std::rc::Rc<dyn LightKind> {
    fn from(__v: Yellow) -> Self {
        std::rc::Rc::new(__v)
    }
}
impl<__JuxH: ?::core::marker::Sized + LightKind> LightKind for std::rc::Rc<__JuxH> {
    fn __jux_as_Green(&self) -> Option<Green> {
        <__JuxH as LightKind>::__jux_as_Green(&**self)
    }
    fn __jux_as_Red(&self) -> Option<Red> {
        <__JuxH as LightKind>::__jux_as_Red(&**self)
    }
    fn __jux_as_Yellow(&self) -> Option<Yellow> {
        <__JuxH as LightKind>::__jux_as_Yellow(&**self)
    }
}
impl PartialEq for dyn LightKind {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::eq(
            crate::JuxIdentity::__jux_identity(self),
            crate::JuxIdentity::__jux_identity(other),
        )
    }
}
impl Eq for dyn LightKind {}
impl std::hash::Hash for dyn LightKind {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        std::ptr::hash(crate::JuxIdentity::__jux_identity(self), state)
    }
}

impl LightKind for Light {}

// JUX:F:/DEV/juxlang/.claude/worktrees/agent-acc64c5fc6ee9d73d/examples/stress_sealed_pat.jux:5:7
#[derive(Clone, Debug)]
pub struct Red_Inner {
    pub __parent: Light_Inner,
    pub seconds: isize,
}

#[derive(Clone, Debug)]
pub(crate) struct Red(pub(crate) std::rc::Rc<std::cell::RefCell<Red_Inner>>);

impl Red {
    pub fn new_inner(s: isize) -> Red_Inner {
        Red_Inner {
            __parent: Light::new_inner(),
            seconds: s,
        }
    }

    pub fn new(s: isize) -> Self {
        Self(std::rc::Rc::new(std::cell::RefCell::new(Self::new_inner(
            s,
        ))))
    }
}

impl std::fmt::Display for Red {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Red@{:p}", std::rc::Rc::as_ptr(&self.0))
    }
}

impl crate::JuxIdentity for Red {
    fn __jux_identity(&self) -> *const () {
        std::rc::Rc::as_ptr(&self.0) as *const ()
    }
}

impl PartialEq for Red {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::eq(std::rc::Rc::as_ptr(&self.0), std::rc::Rc::as_ptr(&other.0))
    }
}
impl Eq for Red {}
impl std::hash::Hash for Red {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        std::ptr::hash(std::rc::Rc::as_ptr(&self.0), state)
    }
}

pub(crate) trait RedKind: LightKind {}
impl RedKind for Red {}
impl LightKind for Red {
    fn __jux_as_Red(&self) -> Option<Red> {
        Some(self.clone())
    }
}

// JUX:F:/DEV/juxlang/.claude/worktrees/agent-acc64c5fc6ee9d73d/examples/stress_sealed_pat.jux:9:7
#[derive(Clone, Debug)]
pub struct Yellow_Inner {
    pub __parent: Light_Inner,
    pub seconds: isize,
}

#[derive(Clone, Debug)]
pub(crate) struct Yellow(pub(crate) std::rc::Rc<std::cell::RefCell<Yellow_Inner>>);

impl Yellow {
    pub fn new_inner(s: isize) -> Yellow_Inner {
        Yellow_Inner {
            __parent: Light::new_inner(),
            seconds: s,
        }
    }

    pub fn new(s: isize) -> Self {
        Self(std::rc::Rc::new(std::cell::RefCell::new(Self::new_inner(
            s,
        ))))
    }
}

impl std::fmt::Display for Yellow {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Yellow@{:p}", std::rc::Rc::as_ptr(&self.0))
    }
}

impl crate::JuxIdentity for Yellow {
    fn __jux_identity(&self) -> *const () {
        std::rc::Rc::as_ptr(&self.0) as *const ()
    }
}

impl PartialEq for Yellow {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::eq(std::rc::Rc::as_ptr(&self.0), std::rc::Rc::as_ptr(&other.0))
    }
}
impl Eq for Yellow {}
impl std::hash::Hash for Yellow {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        std::ptr::hash(std::rc::Rc::as_ptr(&self.0), state)
    }
}

pub(crate) trait YellowKind: LightKind {}
impl YellowKind for Yellow {}
impl LightKind for Yellow {
    fn __jux_as_Yellow(&self) -> Option<Yellow> {
        Some(self.clone())
    }
}

// JUX:F:/DEV/juxlang/.claude/worktrees/agent-acc64c5fc6ee9d73d/examples/stress_sealed_pat.jux:13:7
#[derive(Clone, Debug)]
pub struct Green_Inner {
    pub __parent: Light_Inner,
    pub seconds: isize,
    pub arrow: bool,
}

#[derive(Clone, Debug)]
pub(crate) struct Green(pub(crate) std::rc::Rc<std::cell::RefCell<Green_Inner>>);

impl Green {
    pub fn new_inner(s: isize, arrow: bool) -> Green_Inner {
        Green_Inner {
            __parent: Light::new_inner(),
            seconds: s,
            arrow,
        }
    }

    pub fn new(s: isize, arrow: bool) -> Self {
        Self(std::rc::Rc::new(std::cell::RefCell::new(Self::new_inner(
            s, arrow,
        ))))
    }
}

impl std::fmt::Display for Green {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Green@{:p}", std::rc::Rc::as_ptr(&self.0))
    }
}

impl crate::JuxIdentity for Green {
    fn __jux_identity(&self) -> *const () {
        std::rc::Rc::as_ptr(&self.0) as *const ()
    }
}

impl PartialEq for Green {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::eq(std::rc::Rc::as_ptr(&self.0), std::rc::Rc::as_ptr(&other.0))
    }
}
impl Eq for Green {}
impl std::hash::Hash for Green {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        std::ptr::hash(std::rc::Rc::as_ptr(&self.0), state)
    }
}

pub(crate) trait GreenKind: LightKind {}
impl GreenKind for Green {}
impl LightKind for Green {
    fn __jux_as_Green(&self) -> Option<Green> {
        Some(self.clone())
    }
}

// JUX:F:/DEV/juxlang/.claude/worktrees/agent-acc64c5fc6ee9d73d/examples/stress_sealed_pat.jux:22:8
pub fn describe(l: std::rc::Rc<dyn LightKind>) -> String {
    // JUX:F:/DEV/juxlang/.claude/worktrees/agent-acc64c5fc6ee9d73d/examples/stress_sealed_pat.jux:23:12
    match l {
        ref __jux_subject if __jux_subject.__jux_as_Red().is_some() => {
            let Some(__jux_variant) = __jux_subject.__jux_as_Red() else {
                unreachable!()
            };
            let s = __jux_variant.0.borrow().seconds;
            let __jux_arm = format!("red for {}s", crate::__jux_show!(s));
            __jux_arm
        }
        ref __jux_subject if __jux_subject.__jux_as_Yellow().is_some() => {
            let Some(__jux_variant) = __jux_subject.__jux_as_Yellow() else {
                unreachable!()
            };
            let s = __jux_variant.0.borrow().seconds;
            let __jux_arm = format!("yellow for {}s", crate::__jux_show!(s));
            __jux_arm
        }
        ref __jux_subject if __jux_subject.__jux_as_Green().is_some() => {
            let Some(__jux_variant) = __jux_subject.__jux_as_Green() else {
                unreachable!()
            };
            let s = __jux_variant.0.borrow().seconds;
            let arrow = __jux_variant.0.borrow().arrow;
            let __jux_arm = if arrow {
                format!("green {}s + left arrow", crate::__jux_show!(s))
            } else {
                format!("green {}s", crate::__jux_show!(s))
            };
            __jux_arm
        }
        _ => unreachable!("every permitted type has an arm"),
    }
}

// JUX:F:/DEV/juxlang/.claude/worktrees/agent-acc64c5fc6ee9d73d/examples/stress_sealed_pat.jux:30:8
pub fn __jux_user_main() {
    // JUX:F:/DEV/juxlang/.claude/worktrees/agent-acc64c5fc6ee9d73d/examples/stress_sealed_pat.jux:31:5
    println!(
        "{}",
        describe((std::rc::Rc::new(Red::new(30)) as std::rc::Rc<dyn LightKind>))
    );
    // JUX:F:/DEV/juxlang/.claude/worktrees/agent-acc64c5fc6ee9d73d/examples/stress_sealed_pat.jux:32:5
    println!(
        "{}",
        describe((std::rc::Rc::new(Yellow::new(5)) as std::rc::Rc<dyn LightKind>))
    );
    // JUX:F:/DEV/juxlang/.claude/worktrees/agent-acc64c5fc6ee9d73d/examples/stress_sealed_pat.jux:33:5
    println!(
        "{}",
        describe((std::rc::Rc::new(Green::new(25, true)) as std::rc::Rc<dyn LightKind>))
    );
    // JUX:F:/DEV/juxlang/.claude/worktrees/agent-acc64c5fc6ee9d73d/examples/stress_sealed_pat.jux:34:5
    println!(
        "{}",
        describe((std::rc::Rc::new(Green::new(25, false)) as std::rc::Rc<dyn LightKind>))
    );
}

pub mod jux;

fn main() {
    std::panic::set_hook(::std::boxed::Box::new(|__jux_info| {
        let __jux_p = __jux_info.payload();
        if let Some(__jux_s) = __jux_p.downcast_ref::<&str>() {
            eprintln!("panic: {__jux_s}");
        } else if let Some(__jux_s) = __jux_p.downcast_ref::<String>() {
            eprintln!("panic: {__jux_s}");
        }
    }));
    if let ::std::result::Result::Err(__jux_p) =
        std::panic::catch_unwind(::std::panic::AssertUnwindSafe(__jux_user_main))
    {
        if let Some(__jux_e) =
            __jux_p.downcast_ref::<crate::jux::std::exceptions::ArithmeticException>()
        {
            eprintln!(
                "Exception in thread \"main\" jux.std.exceptions.ArithmeticException: {}",
                __jux_e.getMessage()
            );
        }
        if let Some(__jux_e) =
            __jux_p.downcast_ref::<crate::jux::std::exceptions::CancellationException>()
        {
            eprintln!(
                "Exception in thread \"main\" jux.std.exceptions.CancellationException: {}",
                __jux_e.getMessage()
            );
        }
        if let Some(__jux_e) =
            __jux_p.downcast_ref::<crate::jux::std::exceptions::ClassCastException>()
        {
            eprintln!(
                "Exception in thread \"main\" jux.std.exceptions.ClassCastException: {}",
                __jux_e.getMessage()
            );
        }
        if let Some(__jux_e) =
            __jux_p.downcast_ref::<crate::jux::std::exceptions::EncodingException>()
        {
            eprintln!(
                "Exception in thread \"main\" jux.std.exceptions.EncodingException: {}",
                __jux_e.getMessage()
            );
        }
        if let Some(__jux_e) = __jux_p.downcast_ref::<crate::jux::std::exceptions::Exception>() {
            eprintln!(
                "Exception in thread \"main\" jux.std.exceptions.Exception: {}",
                __jux_e.getMessage()
            );
        }
        if let Some(__jux_e) =
            __jux_p.downcast_ref::<crate::jux::std::exceptions::ExceptionInInitializerError>()
        {
            eprintln!(
                "Exception in thread \"main\" jux.std.exceptions.ExceptionInInitializerError: {}",
                __jux_e.getMessage()
            );
        }
        if let Some(__jux_e) =
            __jux_p.downcast_ref::<crate::jux::std::exceptions::FileNotFoundException>()
        {
            eprintln!(
                "Exception in thread \"main\" jux.std.exceptions.FileNotFoundException: {}",
                __jux_e.getMessage()
            );
        }
        if let Some(__jux_e) = __jux_p.downcast_ref::<crate::jux::std::exceptions::IOException>() {
            eprintln!(
                "Exception in thread \"main\" jux.std.exceptions.IOException: {}",
                __jux_e.getMessage()
            );
        }
        if let Some(__jux_e) =
            __jux_p.downcast_ref::<crate::jux::std::exceptions::IllegalArgumentException>()
        {
            eprintln!(
                "Exception in thread \"main\" jux.std.exceptions.IllegalArgumentException: {}",
                __jux_e.getMessage()
            );
        }
        if let Some(__jux_e) =
            __jux_p.downcast_ref::<crate::jux::std::exceptions::IllegalStateException>()
        {
            eprintln!(
                "Exception in thread \"main\" jux.std.exceptions.IllegalStateException: {}",
                __jux_e.getMessage()
            );
        }
        if let Some(__jux_e) =
            __jux_p.downcast_ref::<crate::jux::std::exceptions::IndexOutOfBoundsException>()
        {
            eprintln!(
                "Exception in thread \"main\" jux.std.exceptions.IndexOutOfBoundsException: {}",
                __jux_e.getMessage()
            );
        }
        if let Some(__jux_e) =
            __jux_p.downcast_ref::<crate::jux::std::exceptions::NoSuchElementException>()
        {
            eprintln!(
                "Exception in thread \"main\" jux.std.exceptions.NoSuchElementException: {}",
                __jux_e.getMessage()
            );
        }
        if let Some(__jux_e) =
            __jux_p.downcast_ref::<crate::jux::std::exceptions::NullPointerException>()
        {
            eprintln!(
                "Exception in thread \"main\" jux.std.exceptions.NullPointerException: {}",
                __jux_e.getMessage()
            );
        }
        if let Some(__jux_e) =
            __jux_p.downcast_ref::<crate::jux::std::exceptions::RuntimeException>()
        {
            eprintln!(
                "Exception in thread \"main\" jux.std.exceptions.RuntimeException: {}",
                __jux_e.getMessage()
            );
        }
        if let Some(__jux_e) =
            __jux_p.downcast_ref::<crate::jux::std::exceptions::TimeoutException>()
        {
            eprintln!(
                "Exception in thread \"main\" jux.std.exceptions.TimeoutException: {}",
                __jux_e.getMessage()
            );
        }
        if let Some(__jux_e) =
            __jux_p.downcast_ref::<crate::jux::std::exceptions::UnsupportedOperationException>()
        {
            eprintln!(
                "Exception in thread \"main\" jux.std.exceptions.UnsupportedOperationException: {}",
                __jux_e.getMessage()
            );
        }
        if let Some(__jux_e) = __jux_p.downcast_ref::<crate::JuxForeignError>() {
            eprintln!(
                "Exception in thread \"main\" {}: {}",
                __jux_e.type_name, __jux_e.text
            );
        }
        std::process::exit(101);
    }
}

/// The default unhandled-rejection hook: report the exception a spawned task
/// threw with nobody awaiting it, then end the process.
pub fn __jux_unhandled_rejection(p: ::std::boxed::Box<dyn ::std::any::Any + ::std::marker::Send>) {
    if let Some(e) = p.downcast_ref::<crate::jux::std::exceptions::ArithmeticException>() {
        eprintln!(
            "Unhandled exception in spawned task: jux.std.exceptions.ArithmeticException: {}",
            e.getMessage()
        );
        std::process::exit(101);
    }
    if let Some(e) = p.downcast_ref::<crate::jux::std::exceptions::CancellationException>() {
        eprintln!(
            "Unhandled exception in spawned task: jux.std.exceptions.CancellationException: {}",
            e.getMessage()
        );
        std::process::exit(101);
    }
    if let Some(e) = p.downcast_ref::<crate::jux::std::exceptions::ClassCastException>() {
        eprintln!(
            "Unhandled exception in spawned task: jux.std.exceptions.ClassCastException: {}",
            e.getMessage()
        );
        std::process::exit(101);
    }
    if let Some(e) = p.downcast_ref::<crate::jux::std::exceptions::EncodingException>() {
        eprintln!(
            "Unhandled exception in spawned task: jux.std.exceptions.EncodingException: {}",
            e.getMessage()
        );
        std::process::exit(101);
    }
    if let Some(e) = p.downcast_ref::<crate::jux::std::exceptions::Exception>() {
        eprintln!(
            "Unhandled exception in spawned task: jux.std.exceptions.Exception: {}",
            e.getMessage()
        );
        std::process::exit(101);
    }
    if let Some(e) = p.downcast_ref::<crate::jux::std::exceptions::ExceptionInInitializerError>() {
        eprintln!("Unhandled exception in spawned task: jux.std.exceptions.ExceptionInInitializerError: {}", e.getMessage());
        std::process::exit(101);
    }
    if let Some(e) = p.downcast_ref::<crate::jux::std::exceptions::FileNotFoundException>() {
        eprintln!(
            "Unhandled exception in spawned task: jux.std.exceptions.FileNotFoundException: {}",
            e.getMessage()
        );
        std::process::exit(101);
    }
    if let Some(e) = p.downcast_ref::<crate::jux::std::exceptions::IOException>() {
        eprintln!(
            "Unhandled exception in spawned task: jux.std.exceptions.IOException: {}",
            e.getMessage()
        );
        std::process::exit(101);
    }
    if let Some(e) = p.downcast_ref::<crate::jux::std::exceptions::IllegalArgumentException>() {
        eprintln!(
            "Unhandled exception in spawned task: jux.std.exceptions.IllegalArgumentException: {}",
            e.getMessage()
        );
        std::process::exit(101);
    }
    if let Some(e) = p.downcast_ref::<crate::jux::std::exceptions::IllegalStateException>() {
        eprintln!(
            "Unhandled exception in spawned task: jux.std.exceptions.IllegalStateException: {}",
            e.getMessage()
        );
        std::process::exit(101);
    }
    if let Some(e) = p.downcast_ref::<crate::jux::std::exceptions::IndexOutOfBoundsException>() {
        eprintln!(
            "Unhandled exception in spawned task: jux.std.exceptions.IndexOutOfBoundsException: {}",
            e.getMessage()
        );
        std::process::exit(101);
    }
    if let Some(e) = p.downcast_ref::<crate::jux::std::exceptions::NoSuchElementException>() {
        eprintln!(
            "Unhandled exception in spawned task: jux.std.exceptions.NoSuchElementException: {}",
            e.getMessage()
        );
        std::process::exit(101);
    }
    if let Some(e) = p.downcast_ref::<crate::jux::std::exceptions::NullPointerException>() {
        eprintln!(
            "Unhandled exception in spawned task: jux.std.exceptions.NullPointerException: {}",
            e.getMessage()
        );
        std::process::exit(101);
    }
    if let Some(e) = p.downcast_ref::<crate::jux::std::exceptions::RuntimeException>() {
        eprintln!(
            "Unhandled exception in spawned task: jux.std.exceptions.RuntimeException: {}",
            e.getMessage()
        );
        std::process::exit(101);
    }
    if let Some(e) = p.downcast_ref::<crate::jux::std::exceptions::TimeoutException>() {
        eprintln!(
            "Unhandled exception in spawned task: jux.std.exceptions.TimeoutException: {}",
            e.getMessage()
        );
        std::process::exit(101);
    }
    if let Some(e) = p.downcast_ref::<crate::jux::std::exceptions::UnsupportedOperationException>()
    {
        eprintln!("Unhandled exception in spawned task: jux.std.exceptions.UnsupportedOperationException: {}", e.getMessage());
        std::process::exit(101);
    }
    if let Some(s) = p.downcast_ref::<&str>() {
        eprintln!("Unhandled panic in spawned task: {s}");
    } else if let Some(s) = p.downcast_ref::<String>() {
        eprintln!("Unhandled panic in spawned task: {s}");
    } else {
        eprintln!("Unhandled failure in spawned task");
    }
    std::process::exit(101);
}
