// AUTO-GENERATED by juxc. DO NOT EDIT.
// Source: examples/stress_sealed_pat.jux

#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_imports)]
#![allow(unused_mut)]
#![allow(unused_parens)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(clippy::all)]

struct JuxOpt<'a, T: std::fmt::Display>(&'a Option<T>);
impl<'a, T: std::fmt::Display> std::fmt::Display for JuxOpt<'a, T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.0 {
            Some(v) => std::fmt::Display::fmt(v, f),
            None => f.write_str("null"),
        }
    }
}

struct __JuxYieldNow(bool);
impl std::future::Future for __JuxYieldNow {
    type Output = ();
    fn poll(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<()> {
        if self.0 {
            std::task::Poll::Ready(())
        } else {
            self.0 = true;
            cx.waker().wake_by_ref();
            std::task::Poll::Pending
        }
    }
}
fn __jux_yield_now() -> __JuxYieldNow {
    __JuxYieldNow(false)
}

pub struct Task<T>(futures::channel::oneshot::Receiver<T>);
impl<T> std::future::Future for Task<T> {
    type Output = T;
    fn poll(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<T> {
        match std::future::Future::poll(std::pin::Pin::new(&mut self.0), cx) {
            std::task::Poll::Ready(Ok(v)) => std::task::Poll::Ready(v),
            std::task::Poll::Ready(Err(_)) => panic!("worker task aborted before completion"),
            std::task::Poll::Pending => std::task::Poll::Pending,
        }
    }
}
pub struct Worker;
impl Worker {
    pub fn spawn<T: Send + 'static, F: FnOnce() -> T + Send + 'static>(f: F) -> Task<T> {
        let (tx, rx) = futures::channel::oneshot::channel();
        std::thread::spawn(move || {
            let _ = tx.send(f());
        });
        Task(rx)
    }
}
fn __jux_now_ms() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

// JUX:examples/stress_sealed_pat.jux:3:15
#[derive(Clone, Debug)]
pub struct Light {}

impl Light {
    pub fn new() -> Self {
        Self {}
    }
}

pub trait LightKind {}
impl LightKind for Light {}

// JUX:examples/stress_sealed_pat.jux:5:14
#[derive(Clone, Debug)]
pub struct Red {
    __parent: Light,
    pub seconds: isize,
}

impl std::ops::Deref for Red {
    type Target = Light;
    fn deref(&self) -> &Self::Target {
        &self.__parent
    }
}

impl std::ops::DerefMut for Red {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.__parent
    }
}

impl Red {
    pub fn new(s: isize) -> Self {
        Self {
            __parent: Light::new(),
            seconds: s,
        }
    }
}

pub trait RedKind {}
impl RedKind for Red {}
impl LightKind for Red {}

// JUX:examples/stress_sealed_pat.jux:9:14
#[derive(Clone, Debug)]
pub struct Yellow {
    __parent: Light,
    pub seconds: isize,
}

impl std::ops::Deref for Yellow {
    type Target = Light;
    fn deref(&self) -> &Self::Target {
        &self.__parent
    }
}

impl std::ops::DerefMut for Yellow {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.__parent
    }
}

impl Yellow {
    pub fn new(s: isize) -> Self {
        Self {
            __parent: Light::new(),
            seconds: s,
        }
    }
}

pub trait YellowKind {}
impl YellowKind for Yellow {}
impl LightKind for Yellow {}

// JUX:examples/stress_sealed_pat.jux:13:14
#[derive(Clone, Debug)]
pub struct Green {
    __parent: Light,
    pub seconds: isize,
    pub arrow: bool,
}

impl std::ops::Deref for Green {
    type Target = Light;
    fn deref(&self) -> &Self::Target {
        &self.__parent
    }
}

impl std::ops::DerefMut for Green {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.__parent
    }
}

impl Green {
    pub fn new(s: isize, arrow: bool) -> Self {
        Self {
            __parent: Light::new(),
            seconds: s,
            arrow,
        }
    }
}

pub trait GreenKind {}
impl GreenKind for Green {}
impl LightKind for Green {}

// JUX:examples/stress_sealed_pat.jux:22:8
fn describe(l: Light) -> String {
    // JUX:examples/stress_sealed_pat.jux:23:12
    match l {
        Red(s) => format!("red for {}s", s),
        Yellow(s) => format!("yellow for {}s", s),
        Green(s, arrow) => {
            if arrow {
                format!("green {}s + left arrow", s)
            } else {
                format!("green {}s", s)
            }
        }
    }
}

// JUX:examples/stress_sealed_pat.jux:30:8
fn main() {
    // JUX:examples/stress_sealed_pat.jux:31:5
    println!("{}", describe(Red::new(30)));
    // JUX:examples/stress_sealed_pat.jux:32:5
    println!("{}", describe(Yellow::new(5)));
    // JUX:examples/stress_sealed_pat.jux:33:5
    println!("{}", describe(Green::new(25, true)));
    // JUX:examples/stress_sealed_pat.jux:34:5
    println!("{}", describe(Green::new(25, false)));
}
