// AUTO-GENERATED by juxc. DO NOT EDIT.
// Source: examples/stress_workers.jux

#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_imports)]
#![allow(unused_mut)]
#![allow(unused_parens)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(clippy::all)]

struct JuxOpt<'a, T: std::fmt::Display>(&'a Option<T>);
impl<'a, T: std::fmt::Display> std::fmt::Display for JuxOpt<'a, T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.0 {
            Some(v) => std::fmt::Display::fmt(v, f),
            None => f.write_str("null"),
        }
    }
}

struct __JuxYieldNow(bool);
impl std::future::Future for __JuxYieldNow {
    type Output = ();
    fn poll(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<()> {
        if self.0 {
            std::task::Poll::Ready(())
        } else {
            self.0 = true;
            cx.waker().wake_by_ref();
            std::task::Poll::Pending
        }
    }
}
fn __jux_yield_now() -> __JuxYieldNow {
    __JuxYieldNow(false)
}

pub struct Task<T>(futures::channel::oneshot::Receiver<T>);
impl<T> std::future::Future for Task<T> {
    type Output = T;
    fn poll(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<T> {
        match std::future::Future::poll(std::pin::Pin::new(&mut self.0), cx) {
            std::task::Poll::Ready(Ok(v)) => std::task::Poll::Ready(v),
            std::task::Poll::Ready(Err(_)) => panic!("worker task aborted before completion"),
            std::task::Poll::Pending => std::task::Poll::Pending,
        }
    }
}
pub struct Worker;
impl Worker {
    pub fn spawn<T: Send + 'static, F: FnOnce() -> T + Send + 'static>(f: F) -> Task<T> {
        let (tx, rx) = futures::channel::oneshot::channel();
        std::thread::spawn(move || {
            let _ = tx.send(f());
        });
        Task(rx)
    }
}
fn __jux_now_ms() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

// JUX:examples/stress_workers.jux:24:8
fn crunch(tag: String, bigN: isize) -> isize {
    // JUX:examples/stress_workers.jux:25:5
    let mut acc: isize = 0;
    // JUX:examples/stress_workers.jux:26:5
    let mut i: isize = 0;
    // JUX:examples/stress_workers.jux:27:5
    while i < bigN {
        // JUX:examples/stress_workers.jux:28:9
        acc = (acc + i) * 7 % 9973;
        // JUX:examples/stress_workers.jux:29:9
        i = i + 1;
    }
    // JUX:examples/stress_workers.jux:31:5
    println!("  [worker {}] done, acc={}", tag, acc);
    // JUX:examples/stress_workers.jux:32:12
    acc
}

// JUX:examples/stress_workers.jux:36:8
async fn run_parallel(bigN: isize) -> isize {
    // JUX:examples/stress_workers.jux:37:5
    println!("--- launching 4 workers ---");
    // JUX:examples/stress_workers.jux:38:11
    let t1 = Worker::spawn(move || crunch("A".to_string(), bigN));
    // JUX:examples/stress_workers.jux:39:11
    let t2 = Worker::spawn(move || crunch("B".to_string(), bigN));
    // JUX:examples/stress_workers.jux:40:11
    let t3 = Worker::spawn(move || crunch("C".to_string(), bigN));
    // JUX:examples/stress_workers.jux:41:11
    let t4 = Worker::spawn(move || crunch("D".to_string(), bigN));
    // JUX:examples/stress_workers.jux:42:11
    let a: isize = t1.await;
    // JUX:examples/stress_workers.jux:43:11
    let b: isize = t2.await;
    // JUX:examples/stress_workers.jux:44:11
    let c: isize = t3.await;
    // JUX:examples/stress_workers.jux:45:11
    let d: isize = t4.await;
    // JUX:examples/stress_workers.jux:46:12
    a + b + c + d
}

// JUX:examples/stress_workers.jux:50:8
fn run_sequential(bigN: isize) -> isize {
    // JUX:examples/stress_workers.jux:51:5
    println!("--- running 4 tasks sequentially on this thread ---");
    // JUX:examples/stress_workers.jux:52:11
    let a: isize = crunch("A".to_string(), bigN);
    // JUX:examples/stress_workers.jux:53:11
    let b: isize = crunch("B".to_string(), bigN);
    // JUX:examples/stress_workers.jux:54:11
    let c: isize = crunch("C".to_string(), bigN);
    // JUX:examples/stress_workers.jux:55:11
    let d: isize = crunch("D".to_string(), bigN);
    // JUX:examples/stress_workers.jux:56:12
    a + b + c + d
}

// JUX:examples/stress_workers.jux:59:8
fn main() {
    // JUX:examples/stress_workers.jux:61:11
    let bigN: isize = 25000000;
    // JUX:examples/stress_workers.jux:63:5
    println!("=== sequential baseline ===");
    // JUX:examples/stress_workers.jux:64:11
    let seq_start: i64 = __jux_now_ms();
    // JUX:examples/stress_workers.jux:65:11
    let seq_sum: isize = run_sequential(bigN);
    // JUX:examples/stress_workers.jux:66:11
    let seq_ms: i64 = __jux_now_ms() - seq_start;
    // JUX:examples/stress_workers.jux:67:5
    println!("sequential sum   = {}", seq_sum);
    // JUX:examples/stress_workers.jux:68:5
    println!("sequential time  = {} ms", seq_ms);
    // JUX:examples/stress_workers.jux:69:5
    println!("");
    // JUX:examples/stress_workers.jux:71:5
    println!("=== parallel workers ===");
    // JUX:examples/stress_workers.jux:72:11
    let par_start: i64 = __jux_now_ms();
    // JUX:examples/stress_workers.jux:73:11
    let par_sum: isize = futures::executor::block_on(run_parallel(bigN));
    // JUX:examples/stress_workers.jux:74:11
    let par_ms: i64 = __jux_now_ms() - par_start;
    // JUX:examples/stress_workers.jux:75:5
    println!("parallel sum     = {}", par_sum);
    // JUX:examples/stress_workers.jux:76:5
    println!("parallel time    = {} ms", par_ms);
    // JUX:examples/stress_workers.jux:77:5
    println!("");
    // JUX:examples/stress_workers.jux:79:5
    if seq_sum == par_sum {
        // JUX:examples/stress_workers.jux:80:9
        println!("OK — sequential and parallel agree on the result.");
        // JUX:examples/stress_workers.jux:81:9
        println!(
            "speedup           = {} % (100% = no speedup)",
            seq_ms * 100 / par_ms
        );
    } else {
        // JUX:examples/stress_workers.jux:83:9
        println!("MISMATCH — implementation bug!");
    }
}
