[package]
name = "sealed_shapes"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
futures = { version = "0.3", features = ["thread-pool"] }

[[bin]]
name = "sealed_shapes"
path = "src/main.rs"

[workspace]

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "symbols"
overflow-checks = false

