// AUTO-GENERATED by juxc. DO NOT EDIT.
// Source: examples/sealed_shapes.jux

#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_imports)]
#![allow(unused_mut)]
#![allow(unused_parens)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(clippy::all)]

struct JuxOpt<'a, T: std::fmt::Display>(&'a Option<T>);
impl<'a, T: std::fmt::Display> std::fmt::Display for JuxOpt<'a, T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.0 {
            Some(v) => std::fmt::Display::fmt(v, f),
            None => f.write_str("null"),
        }
    }
}

struct __JuxYieldNow(bool);
impl std::future::Future for __JuxYieldNow {
    type Output = ();
    fn poll(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<()> {
        if self.0 {
            std::task::Poll::Ready(())
        } else {
            self.0 = true;
            cx.waker().wake_by_ref();
            std::task::Poll::Pending
        }
    }
}
fn __jux_yield_now() -> __JuxYieldNow {
    __JuxYieldNow(false)
}

pub struct Task<T>(futures::channel::oneshot::Receiver<T>);
impl<T> std::future::Future for Task<T> {
    type Output = T;
    fn poll(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<T> {
        match std::future::Future::poll(std::pin::Pin::new(&mut self.0), cx) {
            std::task::Poll::Ready(Ok(v)) => std::task::Poll::Ready(v),
            std::task::Poll::Ready(Err(_)) => panic!("worker task aborted before completion"),
            std::task::Poll::Pending => std::task::Poll::Pending,
        }
    }
}
pub struct Worker;
impl Worker {
    pub fn spawn<T: Send + 'static, F: FnOnce() -> T + Send + 'static>(f: F) -> Task<T> {
        let (tx, rx) = futures::channel::oneshot::channel();
        std::thread::spawn(move || {
            let _ = tx.send(f());
        });
        Task(rx)
    }
}
fn __jux_now_ms() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

// JUX:examples/sealed_shapes.jux:11:15
#[derive(Clone, Debug)]
pub struct Shape {}

impl Shape {
    pub fn new() -> Self {
        Self {}
    }

    pub fn describe(&self) -> String {
        "a shape".to_string()
    }
}

pub trait ShapeKind {}
impl ShapeKind for Shape {}

// JUX:examples/sealed_shapes.jux:17:8
#[derive(Clone, Debug)]
pub struct Circle {
    __parent: Shape,
    pub radius: isize,
}

impl std::ops::Deref for Circle {
    type Target = Shape;
    fn deref(&self) -> &Self::Target {
        &self.__parent
    }
}

impl std::ops::DerefMut for Circle {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.__parent
    }
}

impl Circle {
    pub fn new(radius: isize) -> Self {
        Self {
            __parent: Shape::new(),
            radius,
        }
    }

    pub fn describe(&self) -> String {
        "a shape".to_string()
    }
}

pub trait CircleKind {}
impl CircleKind for Circle {}
impl ShapeKind for Circle {}

// JUX:examples/sealed_shapes.jux:24:8
#[derive(Clone, Debug)]
pub struct Square {
    __parent: Shape,
    pub side: isize,
}

impl std::ops::Deref for Square {
    type Target = Shape;
    fn deref(&self) -> &Self::Target {
        &self.__parent
    }
}

impl std::ops::DerefMut for Square {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.__parent
    }
}

impl Square {
    pub fn new(side: isize) -> Self {
        Self {
            __parent: Shape::new(),
            side,
        }
    }

    pub fn describe(&self) -> String {
        "a shape".to_string()
    }
}

pub trait SquareKind {}
impl SquareKind for Square {}
impl ShapeKind for Square {}

// JUX:examples/sealed_shapes.jux:31:8
fn main() {
    // JUX:examples/sealed_shapes.jux:32:5
    let c = Circle::new(5);
    // JUX:examples/sealed_shapes.jux:33:5
    let s = Square::new(3);
    // JUX:examples/sealed_shapes.jux:34:5
    println!("circle radius={}, {}", c.radius, c.describe());
    // JUX:examples/sealed_shapes.jux:35:5
    println!("square side={}, {}", s.side, s.describe());
}
